/*
USE colorcommercedb;
*/
INSERT INTO cidade (ci_nome, ci_es_cod) VALUES
('Maripá', 18),
('Marmeleiro', 18),
('Marquinho', 18),
('Marumbi', 18),
('Matelândia', 18),
('Matinhos', 18),
('Mato Rico', 18),
('Mauá da Serra', 18),
('Medianeira', 18),
('Mercedes', 18),
('Mirador', 18),
('Miraselva', 18),
('Missal', 18),
('Moreira Sales', 18),
('Morretes', 18),
('Munhoz de Melo', 18),
('Nossa Senhora das Graças', 18),
('Nova Aliança do Ivaí', 18),
('Nova América da Colina', 18),
('Nova Aurora', 18),
('Nova Cantu', 18),
('Nova Esperança', 18),
('Nova Esperança do Sudoeste', 18),
('Nova Fátima', 18),
('Nova Laranjeiras', 18),
('Nova Londrina', 18),
('Nova Olímpia', 18),
('Nova Prata do Iguaçu', 18),
('Nova Santa Bárbara', 18),
('Nova Santa Rosa', 18),
('Nova Tebas', 18),
('Novo Itacolomi', 18),
('Ortigueira', 18),
('Ourizona', 18),
('Ouro Verde do Oeste', 18),
('Paiçandu', 18),
('Palmas', 18),
('Palmeira', 18),
('Palmital', 18),
('Palotina', 18),
('Paraíso do Norte', 18),
('Paranacity', 18),
('Paranaguá', 18),
('Paranapoema', 18),
('Paranavaí', 18),
('Pato Bragado', 18),
('Pato Branco', 18),
('Paula Freitas', 18),
('Paulo Frontin', 18),
('Peabiru', 18),
('Perobal', 18),
('Pérola', 18),
('Pérola d`Oeste', 18),
('Piên', 18),
('Pinhais', 18),
('Pinhal de São Bento', 18),
('Pinhalão', 18),
('Pinhão', 18),
('Piraí do Sul', 18),
('Piraquara', 18),
('Pitanga', 18),
('Pitangueiras', 18),
('Planaltina do Paraná', 18),
('Planalto', 18),
('Ponta Grossa', 18),
('Pontal do Paraná', 18),
('Porecatu', 18),
('Porto Amazonas', 18),
('Porto Barreiro', 18),
('Porto Rico', 18),
('Porto Vitória', 18),
('Prado Ferreira', 18),
('Pranchita', 18),
('Presidente Castelo Branco', 18),
('Primeiro de Maio', 18),
('Prudentópolis', 18),
('Quarto Centenário', 18),
('Quatiguá', 18),
('Quatro Barras', 18),
('Quatro Pontes', 18),
('Quedas do Iguaçu', 18),
('Querência do Norte', 18),
('Quinta do Sol', 18),
('Quitandinha', 18),
('Ramilândia', 18),
('Rancho Alegre', 18),
('Rancho Alegre d`Oeste', 18),
('Realeza', 18),
('Rebouças', 18),
('Renascença', 18),
('Reserva', 18),
('Reserva do Iguaçu', 18),
('Ribeirão Claro', 18),
('Ribeirão do Pinhal', 18),
('Rio Azul', 18),
('Rio Bom', 18),
('Rio Bonito do Iguaçu', 18),
('Rio Branco do Ivaí', 18),
('Rio Branco do Sul', 18),
('Rio Negro', 18),
('Rolândia', 18),
('Roncador', 18),
('Rondon', 18),
('Rosário do Ivaí', 18),
('Sabáudia', 18),
('Salgado Filho', 18),
('Salto do Itararé', 18),
('Salto do Lontra', 18),
('Santa Amélia', 18),
('Santa Cecília do Pavão', 18),
('Santa Cruz de Monte Castelo', 18),
('Santa Fé', 18),
('Santa Helena', 18),
('Santa Inês', 18),
('Santa Isabel do Ivaí', 18),
('Santa Izabel do Oeste', 18),
('Santa Lúcia', 18),
('Santa Maria do Oeste', 18),
('Santa Mariana', 18),
('Santa Mônica', 18),
('Santa Tereza do Oeste', 18),
('Santa Terezinha de Itaipu', 18),
('Santana do Itararé', 18),
('Santo Antônio da Platina', 18),
('Santo Antônio do Caiuá', 18),
('Santo Antônio do Paraíso', 18),
('Santo Antônio do Sudoeste', 18),
('Santo Inácio', 18),
('São Carlos do Ivaí', 18),
('São Jerônimo da Serra', 18),
('São João', 18),
('São João do Caiuá', 18),
('São João do Ivaí', 18),
('São João do Triunfo', 18),
('São Jorge d`Oeste', 18),
('São Jorge do Ivaí', 18),
('São Jorge do Patrocínio', 18),
('São José da Boa Vista', 18),
('São José das Palmeiras', 18),
('São José dos Pinhais', 18),
('São Manoel do Paraná', 18),
('São Mateus do Sul', 18),
('São Miguel do Iguaçu', 18),
('São Pedro do Iguaçu', 18),
('São Pedro do Ivaí', 18),
('São Pedro do Paraná', 18),
('São Sebastião da Amoreira', 18),
('São Tomé', 18),
('Sapopema', 18),
('Sarandi', 18),
('Saudade do Iguaçu', 18),
('Sengés', 18),
('Serranópolis do Iguaçu', 18),
('Sertaneja', 18),
('Sertanópolis', 18),
('Siqueira Campos', 18),
('Sulina', 18),
('Tamarana', 18),
('Tamboara', 18),
('Tapejara', 18),
('Tapira', 18),
('Teixeira Soares', 18),
('Telêmaco Borba', 18),
('Terra Boa', 18),
('Terra Rica', 18),
('Terra Roxa', 18),
('Tibagi', 18),
('Tijucas do Sul', 18),
('Toledo', 18),
('Tomazina', 18),
('Três Barras do Paraná', 18),
('Tunas do Paraná', 18),
('Tuneiras do Oeste', 18),
('Tupãssi', 18),
('Turvo', 18),
('Ubiratã', 18),
('Umuarama', 18),
('União da Vitória', 18),
('Uniflor', 18),
('Uraí', 18),
('Ventania', 18),
('Vera Cruz do Oeste', 18),
('Verê', 18),
('Virmond', 18),
('Vitorino', 18),
('Wenceslau Braz', 18),
('Xambrê', 18),
('Abreu e Lima', 16),
('Afogados da Ingazeira', 16),
('Afrânio', 16),
('Agrestina', 16),
('Água Preta', 16),
('Águas Belas', 16),
('Alagoinha', 16),
('Aliança', 16),
('Altinho', 16),
('Amaraji', 16),
('Angelim', 16),
('Araçoiaba', 16),
('Araripina', 16),
('Arcoverde', 16),
('Barra de Guabiraba', 16),
('Barreiros', 16),
('Belém de Maria', 16),
('Belém de São Francisco', 16),
('Belo Jardim', 16),
('Betânia', 16),
('Bezerros', 16),
('Bodocó', 16),
('Bom Conselho', 16),
('Bom Jardim', 16),
('Bonito', 16),
('Brejão', 16),
('Brejinho', 16),
('Brejo da Madre de Deus', 16),
('Buenos Aires', 16),
('Buíque', 16),
('Cabo de Santo Agostinho', 16),
('Cabrobó', 16),
('Cachoeirinha', 16),
('Caetés', 16),
('Calçado', 16),
('Calumbi', 16),
('Camaragibe', 16),
('Camocim de São Félix', 16),
('Camutanga', 16),
('Canhotinho', 16),
('Capoeiras', 16),
('Carnaíba', 16),
('Carnaubeira da Penha', 16),
('Carpina', 16),
('Caruaru', 16),
('Casinhas', 16),
('Catende', 16),
('Cedro', 16),
('Chã de Alegria', 16),
('Chã Grande', 16),
('Condado', 16),
('Correntes', 16),
('Cortês', 16),
('Cumaru', 16),
('Cupira', 16),
('Custódia', 16),
('Dormentes', 16),
('Escada', 16),
('Exu', 16),
('Feira Nova', 16),
('Fernando de Noronha', 16),
('Ferreiros', 16),
('Flores', 16),
('Floresta', 16),
('Frei Miguelinho', 16),
('Gameleira', 16),
('Garanhuns', 16),
('Glória do Goitá', 16),
('Goiana', 16),
('Granito', 16),
('Gravatá', 16),
('Iati', 16),
('Ibimirim', 16),
('Ibirajuba', 16),
('Igarassu', 16),
('Iguaraci', 16),
('Ilha de Itamaracá', 16),
('Inajá', 16),
('Ingazeira', 16),
('Ipojuca', 16),
('Ipubi', 16),
('Itacuruba', 16),
('Itaíba', 16),
('Itambé', 16),
('Itapetim', 16),
('Itapissuma', 16),
('Itaquitinga', 16),
('Jaboatão dos Guararapes', 16),
('Jaqueira', 16),
('Jataúba', 16),
('Jatobá', 16),
('João Alfredo', 16),
('Joaquim Nabuco', 16),
('Jucati', 16),
('Jupi', 16),
('Jurema', 16),
('Lagoa do Carro', 16),
('Lagoa do Itaenga', 16),
('Lagoa do Ouro', 16),
('Lagoa dos Gatos', 16),
('Lagoa Grande', 16),
('Lajedo', 16),
('Limoeiro', 16),
('Macaparana', 16),
('Machados', 16),
('Manari', 16),
('Maraial', 16),
('Mirandiba', 16),
('Moreilândia', 16),
('Moreno', 16),
('Nazaré da Mata', 16),
('Olinda', 16),
('Orobó', 16),
('Orocó', 16),
('Ouricuri', 16),
('Palmares', 16),
('Palmeirina', 16),
('Panelas', 16),
('Paranatama', 16),
('Parnamirim', 16),
('Passira', 16),
('Paudalho', 16),
('Paulista', 16),
('Pedra', 16),
('Pesqueira', 16),
('Petrolândia', 16),
('Petrolina', 16),
('Poção', 16),
('Pombos', 16),
('Primavera', 16),
('Quipapá', 16),
('Quixaba', 16),
('Recife', 16),
('Riacho das Almas', 16),
('Ribeirão', 16),
('Rio Formoso', 16),
('Sairé', 16),
('Salgadinho', 16),
('Salgueiro', 16),
('Saloá', 16),
('Sanharó', 16),
('Santa Cruz', 16),
('Santa Cruz da Baixa Verde', 16),
('Santa Cruz do Capibaribe', 16),
('Santa Filomena', 16),
('Santa Maria da Boa Vista', 16),
('Santa Maria do Cambucá', 16),
('Santa Terezinha', 16),
('São Benedito do Sul', 16),
('São Bento do Una', 16),
('São Caitano', 16),
('São João', 16),
('São Joaquim do Monte', 16),
('São José da Coroa Grande', 16),
('São José do Belmonte', 16),
('São José do Egito', 16),
('São Lourenço da Mata', 16),
('São Vicente Ferrer', 16),
('Serra Talhada', 16),
('Serrita', 16),
('Sertânia', 16),
('Sirinhaém', 16),
('Solidão', 16),
('Surubim', 16),
('Tabira', 16),
('Tacaimbó', 16),
('Tacaratu', 16),
('Tamandaré', 16),
('Taquaritinga do Norte', 16),
('Terezinha', 16),
('Terra Nova', 16),
('Timbaúba', 16),
('Toritama', 16),
('Tracunhaém', 16),
('Trindade', 16),
('Triunfo', 16),
('Tupanatinga', 16),
('Tuparetama', 16),
('Venturosa', 16),
('Verdejante', 16),
('Vertente do Lério', 16),
('Vertentes', 16),
('Vicência', 16),
('Vitória de Santo Antão', 16),
('Xexéu', 16),
('Acauã', 17),
('Agricolândia', 17),
('Água Branca', 17),
('Alagoinha do Piauí', 17),
('Alegrete do Piauí', 17),
('Alto Longá', 17),
('Altos', 17),
('Alvorada do Gurguéia', 17),
('Amarante', 17),
('Angical do Piauí', 17),
('Anísio de Abreu', 17),
('Antônio Almeida', 17),
('Aroazes', 17),
('Aroeiras do Itaim', 17),
('Arraial', 17),
('Assunção do Piauí', 17),
('Avelino Lopes', 17),
('Baixa Grande do Ribeiro', 17),
('Barra d`Alcântara', 17),
('Barras', 17),
('Barreiras do Piauí', 17),
('Barro Duro', 17),
('Batalha', 17),
('Bela Vista do Piauí', 17),
('Belém do Piauí', 17),
('Beneditinos', 17),
('Bertolínia', 17),
('Betânia do Piauí', 17),
('Boa Hora', 17),
('Bocaina', 17),
('Bom Jesus', 17),
('Bom Princípio do Piauí', 17),
('Bonfim do Piauí', 17),
('Boqueirão do Piauí', 17),
('Brasileira', 17),
('Brejo do Piauí', 17),
('Buriti dos Lopes', 17),
('Buriti dos Montes', 17),
('Cabeceiras do Piauí', 17),
('Cajazeiras do Piauí', 17),
('Cajueiro da Praia', 17),
('Caldeirão Grande do Piauí', 17),
('Campinas do Piauí', 17),
('Campo Alegre do Fidalgo', 17),
('Campo Grande do Piauí', 17),
('Campo Largo do Piauí', 17),
('Campo Maior', 17),
('Canavieira', 17),
('Canto do Buriti', 17),
('Capitão de Campos', 17),
('Capitão Gervásio Oliveira', 17),
('Caracol', 17),
('Caraúbas do Piauí', 17),
('Caridade do Piauí', 17),
('Castelo do Piauí', 17),
('Caxingó', 17),
('Cocal', 17),
('Cocal de Telha', 17),
('Cocal dos Alves', 17),
('Coivaras', 17),
('Colônia do Gurguéia', 17),
('Colônia do Piauí', 17),
('Conceição do Canindé', 17),
('Coronel José Dias', 17),
('Corrente', 17),
('Cristalândia do Piauí', 17),
('Cristino Castro', 17),
('Curimatá', 17),
('Currais', 17),
('Curral Novo do Piauí', 17),
('Curralinhos', 17),
('Demerval Lobão', 17),
('Dirceu Arcoverde', 17),
('Dom Expedito Lopes', 17),
('Dom Inocêncio', 17),
('Domingos Mourão', 17),
('Elesbão Veloso', 17),
('Eliseu Martins', 17),
('Esperantina', 17),
('Fartura do Piauí', 17),
('Flores do Piauí', 17),
('Floresta do Piauí', 17),
('Floriano', 17),
('Francinópolis', 17),
('Francisco Ayres', 17),
('Francisco Macedo', 17),
('Francisco Santos', 17),
('Fronteiras', 17),
('Geminiano', 17),
('Gilbués', 17),
('Guadalupe', 17),
('Guaribas', 17),
('Hugo Napoleão', 17),
('Ilha Grande', 17),
('Inhuma', 17),
('Ipiranga do Piauí', 17),
('Isaías Coelho', 17),
('Itainópolis', 17),
('Itaueira', 17),
('Jacobina do Piauí', 17),
('Jaicós', 17),
('Jardim do Mulato', 17),
('Jatobá do Piauí', 17),
('Jerumenha', 17),
('João Costa', 17),
('Joaquim Pires', 17),
('Joca Marques', 17),
('José de Freitas', 17),
('Juazeiro do Piauí', 17),
('Júlio Borges', 17),
('Jurema', 17),
('Lagoa Alegre', 17),
('Lagoa de São Francisco', 17),
('Lagoa do Barro do Piauí', 17),
('Lagoa do Piauí', 17),
('Lagoa do Sítio', 17),
('Lagoinha do Piauí', 17),
('Landri Sales', 17),
('Luís Correia', 17),
('Luzilândia', 17),
('Madeiro', 17),
('Manoel Emídio', 17),
('Marcolândia', 17),
('Marcos Parente', 17),
('Massapê do Piauí', 17),
('Matias Olímpio', 17),
('Miguel Alves', 17),
('Miguel Leão', 17),
('Milton Brandão', 17),
('Monsenhor Gil', 17),
('Monsenhor Hipólito', 17),
('Monte Alegre do Piauí', 17),
('Morro Cabeça no Tempo', 17),
('Morro do Chapéu do Piauí', 17),
('Murici dos Portelas', 17),
('Nazaré do Piauí', 17),
('Nossa Senhora de Nazaré', 17),
('Nossa Senhora dos Remédios', 17),
('Nova Santa Rita', 17),
('Novo Oriente do Piauí', 17),
('Novo Santo Antônio', 17),
('Oeiras', 17),
('Olho d`Água do Piauí', 17),
('Padre Marcos', 17),
('Paes Landim', 17),
('Pajeú do Piauí', 17),
('Palmeira do Piauí', 17),
('Palmeirais', 17),
('Paquetá', 17),
('Parnaguá', 17),
('Parnaíba', 17),
('Passagem Franca do Piauí', 17),
('Patos do Piauí', 17),
('Pau d`Arco do Piauí', 17),
('Paulistana', 17),
('Pavussu', 17),
('Pedro II', 17),
('Pedro Laurentino', 17),
('Picos', 17),
('Pimenteiras', 17),
('Pio IX', 17),
('Piracuruca', 17),
('Piripiri', 17),
('Porto', 17),
('Porto Alegre do Piauí', 17),
('Prata do Piauí', 17),
('Queimada Nova', 17),
('Redenção do Gurguéia', 17),
('Regeneração', 17),
('Riacho Frio', 17),
('Ribeira do Piauí', 17),
('Ribeiro Gonçalves', 17),
('Rio Grande do Piauí', 17),
('Santa Cruz do Piauí', 17),
('Santa Cruz dos Milagres', 17),
('Santa Filomena', 17),
('Santa Luz', 17),
('Santa Rosa do Piauí', 17),
('Santana do Piauí', 17),
('Santo Antônio de Lisboa', 17),
('Santo Antônio dos Milagres', 17),
('Santo Inácio do Piauí', 17),
('São Braz do Piauí', 17),
('São Félix do Piauí', 17),
('São Francisco de Assis do Piauí', 17),
('São Francisco do Piauí', 17),
('São Gonçalo do Gurguéia', 17),
('São Gonçalo do Piauí', 17),
('São João da Canabrava', 17),
('São João da Fronteira', 17),
('São João da Serra', 17),
('São João da Varjota', 17),
('São João do Arraial', 17),
('São João do Piauí', 17),
('São José do Divino', 17),
('São José do Peixe', 17),
('São José do Piauí', 17),
('São Julião', 17),
('São Lourenço do Piauí', 17),
('São Luis do Piauí', 17),
('São Miguel da Baixa Grande', 17),
('São Miguel do Fidalgo', 17),
('São Miguel do Tapuio', 17),
('São Pedro do Piauí', 17),
('São Raimundo Nonato', 17),
('Sebastião Barros', 17),
('Sebastião Leal', 17),
('Sigefredo Pacheco', 17),
('Simões', 17),
('Simplício Mendes', 17),
('Socorro do Piauí', 17),
('Sussuapara', 17),
('Tamboril do Piauí', 17),
('Tanque do Piauí', 17),
('Teresina', 17),
('União', 17),
('Uruçuí', 17),
('Valença do Piauí', 17),
('Várzea Branca', 17),
('Várzea Grande', 17),
('Vera Mendes', 17),
('Vila Nova do Piauí', 17),
('Wall Ferraz', 17),
('Angra dos Reis', 19),
('Aperibé', 19),
('Araruama', 19),
('Areal', 19),
('Armação dos Búzios', 19),
('Arraial do Cabo', 19),
('Barra do Piraí', 19),
('Barra Mansa', 19),
('Belford Roxo', 19),
('Bom Jardim', 19),
('Bom Jesus do Itabapoana', 19),
('Cabo Frio', 19),
('Cachoeiras de Macacu', 19),
('Cambuci', 19),
('Campos dos Goytacazes', 19),
('Cantagalo', 19),
('Carapebus', 19),
('Cardoso Moreira', 19),
('Carmo', 19),
('Casimiro de Abreu', 19),
('Comendador Levy Gasparian', 19),
('Conceição de Macabu', 19),
('Cordeiro', 19),
('Duas Barras', 19),
('Duque de Caxias', 19),
('Engenheiro Paulo de Frontin', 19),
('Guapimirim', 19),
('Iguaba Grande', 19),
('Itaboraí', 19),
('Itaguaí', 19),
('Italva', 19),
('Itaocara', 19),
('Itaperuna', 19),
('Itatiaia', 19),
('Japeri', 19),
('Laje do Muriaé', 19),
('Macaé', 19),
('Macuco', 19),
('Magé', 19),
('Mangaratiba', 19),
('Maricá', 19),
('Mendes', 19),
('Mesquita', 19),
('Miguel Pereira', 19),
('Miracema', 19),
('Natividade', 19),
('Nilópolis', 19),
('Niterói', 19),
('Nova Friburgo', 19),
('Nova Iguaçu', 19),
('Paracambi', 19),
('Paraíba do Sul', 19),
('Parati', 19),
('Paty do Alferes', 19),
('Petrópolis', 19),
('Pinheiral', 19),
('Piraí', 19),
('Porciúncula', 19),
('Porto Real', 19),
('Quatis', 19),
('Queimados', 19),
('Quissamã', 19),
('Resende', 19),
('Rio Bonito', 19),
('Rio Claro', 19),
('Rio das Flores', 19),
('Rio das Ostras', 19),
('Rio de Janeiro', 19),
('Santa Maria Madalena', 19),
('Santo Antônio de Pádua', 19),
('São Fidélis', 19),
('São Francisco de Itabapoana', 19),
('São Gonçalo', 19),
('São João da Barra', 19),
('São João de Meriti', 19),
('São José de Ubá', 19),
('São José do Vale do Rio Pret', 19),
('São Pedro da Aldeia', 19),
('São Sebastião do Alto', 19),
('Sapucaia', 19),
('Saquarema', 19),
('Seropédica', 19),
('Silva Jardim', 19),
('Sumidouro', 19),
('Tanguá', 19),
('Teresópolis', 19),
('Trajano de Morais', 19),
('Três Rios', 19),
('Valença', 19),
('Varre-Sai', 19),
('Vassouras', 19),
('Volta Redonda', 19),
('Acari', 20),
('Açu', 20),
('Afonso Bezerra', 20),
('Água Nova', 20),
('Alexandria', 20),
('Almino Afonso', 20),
('Alto do Rodrigues', 20),
('Angicos', 20),
('Antônio Martins', 20),
('Apodi', 20),
('Areia Branca', 20),
('Arês', 20),
('Augusto Severo', 20),
('Baía Formosa', 20),
('Baraúna', 20),
('Barcelona', 20),
('Bento Fernandes', 20),
('Bodó', 20),
('Bom Jesus', 20),
('Brejinho', 20),
('Caiçara do Norte', 20),
('Caiçara do Rio do Vento', 20),
('Caicó', 20),
('Campo Redondo', 20),
('Canguaretama', 20),
('Caraúbas', 20),
('Carnaúba dos Dantas', 20),
('Carnaubais', 20),
('Ceará-Mirim', 20),
('Cerro Corá', 20),
('Coronel Ezequiel', 20),
('Coronel João Pessoa', 20),
('Cruzeta', 20),
('Currais Novos', 20),
('Doutor Severiano', 20),
('Encanto', 20),
('Equador', 20),
('Espírito Santo', 20),
('Extremoz', 20),
('Felipe Guerra', 20),
('Fernando Pedroza', 20),
('Florânia', 20),
('Francisco Dantas', 20),
('Frutuoso Gomes', 20),
('Galinhos', 20),
('Goianinha', 20),
('Governador Dix-Sept Rosado', 20),
('Grossos', 20),
('Guamaré', 20),
('Ielmo Marinho', 20),
('Ipanguaçu', 20),
('Ipueira', 20),
('Itajá', 20),
('Itaú', 20),
('Jaçanã', 20),
('Jandaíra', 20),
('Janduís', 20),
('Januário Cicco', 20),
('Japi', 20),
('Jardim de Angicos', 20),
('Jardim de Piranhas', 20),
('Jardim do Seridó', 20),
('João Câmara', 20),
('João Dias', 20),
('José da Penha', 20),
('Jucurutu', 20),
('Jundiá', 20),
('Lagoa d`Anta', 20),
('Lagoa de Pedras', 20),
('Lagoa de Velhos', 20),
('Lagoa Nova', 20),
('Lagoa Salgada', 20),
('Lajes', 20),
('Lajes Pintadas', 20),
('Lucrécia', 20),
('Luís Gomes', 20),
('Macaíba', 20),
('Macau', 20),
('Major Sales', 20),
('Marcelino Vieira', 20),
('Martins', 20),
('Maxaranguape', 20),
('Messias Targino', 20),
('Montanhas', 20),
('Monte Alegre', 20),
('Monte das Gameleiras', 20),
('Mossoró', 20),
('Natal', 20),
('Nísia Floresta', 20),
('Nova Cruz', 20),
('Olho-d`Água do Borges', 20),
('Ouro Branco', 20),
('Paraná', 20),
('Paraú', 20),
('Parazinho', 20),
('Parelhas', 20),
('Parnamirim', 20),
('Passa e Fica', 20),
('Passagem', 20),
('Patu', 20),
('Pau dos Ferros', 20),
('Pedra Grande', 20),
('Pedra Preta', 20),
('Pedro Avelino', 20),
('Pedro Velho', 20),
('Pendências', 20),
('Pilões', 20),
('Poço Branco', 20),
('Portalegre', 20),
('Porto do Mangue', 20),
('Presidente Juscelino', 20),
('Pureza', 20),
('Rafael Fernandes', 20),
('Rafael Godeiro', 20),
('Riacho da Cruz', 20),
('Riacho de Santana', 20),
('Riachuelo', 20),
('Rio do Fogo', 20),
('Rodolfo Fernandes', 20),
('Ruy Barbosa', 20),
('Santa Cruz', 20),
('Santa Maria', 20),
('Santana do Matos', 20),
('Santana do Seridó', 20),
('Santo Antônio', 20),
('São Bento do Norte', 20),
('São Bento do Trairí', 20),
('São Fernando', 20),
('São Francisco do Oeste', 20),
('São Gonçalo do Amarante', 20),
('São João do Sabugi', 20),
('São José de Mipibu', 20),
('São José do Campestre', 20),
('São José do Seridó', 20),
('São Miguel', 20),
('São Miguel do Gostoso', 20),
('São Paulo do Potengi', 20),
('São Pedro', 20),
('São Rafael', 20),
('São Tomé', 20),
('São Vicente', 20),
('Senador Elói de Souza', 20),
('Senador Georgino Avelino', 20),
('Serra de São Bento', 20),
('Serra do Mel', 20),
('Serra Negra do Norte', 20),
('Serrinha', 20),
('Serrinha dos Pintos', 20),
('Severiano Melo', 20),
('Sítio Novo', 20),
('Taboleiro Grande', 20),
('Taipu', 20),
('Tangará', 20),
('Tenente Ananias', 20),
('Tenente Laurentino Cruz', 20),
('Tibau', 20),
('Tibau do Sul', 20),
('Timbaúba dos Batistas', 20),
('Touros', 20),
('Triunfo Potiguar', 20),
('Umarizal', 20),
('Upanema', 20),
('Várzea', 20),
('Venha-Ver', 20),
('Vera Cruz', 20),
('Viçosa', 20),
('Vila Flor', 20),
('Aceguá', 23),
('Água Santa', 23),
('Agudo', 23),
('Ajuricaba', 23),
('Alecrim', 23),
('Alegrete', 23),
('Alegria', 23),
('Almirante Tamandaré do Sul', 23),
('Alpestre', 23),
('Alto Alegre', 23),
('Alto Feliz', 23),
('Alvorada', 23),
('Amaral Ferrador', 23),
('Ametista do Sul', 23),
('André da Rocha', 23),
('Anta Gorda', 23),
('Antônio Prado', 23),
('Arambaré', 23),
('Araricá', 23),
('Aratiba', 23),
('Arroio do Meio', 23),
('Arroio do Padre', 23),
('Arroio do Sal', 23),
('Arroio do Tigre', 23),
('Arroio dos Ratos', 23),
('Arroio Grande', 23),
('Arvorezinha', 23),
('Augusto Pestana', 23),
('Áurea', 23),
('Bagé', 23),
('Balneário Pinhal', 23),
('Barão', 23),
('Barão de Cotegipe', 23),
('Barão do Triunfo', 23),
('Barra do Guarita', 23),
('Barra do Quaraí', 23),
('Barra do Ribeiro', 23),
('Barra do Rio Azul', 23),
('Barra Funda', 23),
('Barracão', 23),
('Barros Cassal', 23),
('Benjamin Constant do Sul', 23),
('Bento Gonçalves', 23),
('Boa Vista das Missões', 23),
('Boa Vista do Buricá', 23),
('Boa Vista do Cadeado', 23),
('Boa Vista do Incra', 23),
('Boa Vista do Sul', 23),
('Bom Jesus', 23),
('Bom Princípio', 23),
('Bom Progresso', 23),
('Bom Retiro do Sul', 23),
('Boqueirão do Leão', 23),
('Bossoroca', 23),
('Bozano', 23),
('Braga', 23),
('Brochier', 23),
('Butiá', 23),
('Caçapava do Sul', 23),
('Cacequi', 23),
('Cachoeira do Sul', 23),
('Cachoeirinha', 23),
('Cacique Doble', 23),
('Caibaté', 23),
('Caiçara', 23),
('Camaquã', 23),
('Camargo', 23),
('Cambará do Sul', 23),
('Campestre da Serra', 23),
('Campina das Missões', 23),
('Campinas do Sul', 23),
('Campo Bom', 23),
('Campo Novo', 23),
('Campos Borges', 23),
('Candelária', 23),
('Cândido Godói', 23),
('Candiota', 23),
('Canela', 23),
('Canguçu', 23),
('Canoas', 23),
('Canudos do Vale', 23),
('Capão Bonito do Sul', 23),
('Capão da Canoa', 23),
('Capão do Cipó', 23),
('Capão do Leão', 23),
('Capela de Santana', 23),
('Capitão', 23),
('Capivari do Sul', 23),
('Caraá', 23),
('Carazinho', 23),
('Carlos Barbosa', 23),
('Carlos Gomes', 23),
('Casca', 23),
('Caseiros', 23),
('Catuípe', 23),
('Caxias do Sul', 23),
('Centenário', 23),
('Cerrito', 23),
('Cerro Branco', 23),
('Cerro Grande', 23),
('Cerro Grande do Sul', 23),
('Cerro Largo', 23),
('Chapada', 23),
('Charqueadas', 23),
('Charrua', 23),
('Chiapeta', 23),
('Chuí', 23),
('Chuvisca', 23),
('Cidreira', 23),
('Ciríaco', 23),
('Colinas', 23),
('Colorado', 23),
('Condor', 23),
('Constantina', 23),
('Coqueiro Baixo', 23),
('Coqueiros do Sul', 23),
('Coronel Barros', 23),
('Coronel Bicaco', 23),
('Coronel Pilar', 23),
('Cotiporã', 23),
('Coxilha', 23),
('Crissiumal', 23),
('Cristal', 23),
('Cristal do Sul', 23),
('Cruz Alta', 23),
('Cruzaltense', 23),
('Cruzeiro do Sul', 23),
('David Canabarro', 23),
('Derrubadas', 23),
('Dezesseis de Novembro', 23),
('Dilermando de Aguiar', 23),
('Dois Irmãos', 23),
('Dois Irmãos das Missões', 23),
('Dois Lajeados', 23),
('Dom Feliciano', 23),
('Dom Pedrito', 23),
('Dom Pedro de Alcântara', 23),
('Dona Francisca', 23),
('Doutor Maurício Cardoso', 23),
('Doutor Ricardo', 23),
('Eldorado do Sul', 23),
('Encantado', 23),
('Encruzilhada do Sul', 23),
('Engenho Velho', 23);