/*
USE colorcommercedb;
*/
INSERT INTO cidade (ci_nome, ci_es_cod) VALUES
('Entre Rios do Sul', 23),
('Entre-Ijuís', 23),
('Erebango', 23),
('Erechim', 23),
('Ernestina', 23),
('Erval Grande', 23),
('Erval Seco', 23),
('Esmeralda', 23),
('Esperança do Sul', 23),
('Espumoso', 23),
('Estação', 23),
('Estância Velha', 23),
('Esteio', 23),
('Estrela', 23),
('Estrela Velha', 23),
('Eugênio de Castro', 23),
('Fagundes Varela', 23),
('Farroupilha', 23),
('Faxinal do Soturno', 23),
('Faxinalzinho', 23),
('Fazenda Vilanova', 23),
('Feliz', 23),
('Flores da Cunha', 23),
('Floriano Peixoto', 23),
('Fontoura Xavier', 23),
('Formigueiro', 23),
('Forquetinha', 23),
('Fortaleza dos Valos', 23),
('Frederico Westphalen', 23),
('Garibaldi', 23),
('Garruchos', 23),
('Gaurama', 23),
('General Câmara', 23),
('Gentil', 23),
('Getúlio Vargas', 23),
('Giruá', 23),
('Glorinha', 23),
('Gramado', 23),
('Gramado dos Loureiros', 23),
('Gramado Xavier', 23),
('Gravataí', 23),
('Guabiju', 23),
('Guaíba', 23),
('Guaporé', 23),
('Guarani das Missões', 23),
('Harmonia', 23),
('Herval', 23),
('Herveiras', 23),
('Horizontina', 23),
('Hulha Negra', 23),
('Humaitá', 23),
('Ibarama', 23),
('Ibiaçá', 23),
('Ibiraiaras', 23),
('Ibirapuitã', 23),
('Ibirubá', 23),
('Igrejinha', 23),
('Ijuí', 23),
('Ilópolis', 23),
('Imbé', 23),
('Imigrante', 23),
('Independência', 23),
('Inhacorá', 23),
('Ipê', 23),
('Ipiranga do Sul', 23),
('Iraí', 23),
('Itaara', 23),
('Itacurubi', 23),
('Itapuca', 23),
('Itaqui', 23),
('Itati', 23),
('Itatiba do Sul', 23),
('Ivorá', 23),
('Ivoti', 23),
('Jaboticaba', 23),
('Jacuizinho', 23),
('Jacutinga', 23),
('Jaguarão', 23),
('Jaguari', 23),
('Jaquirana', 23),
('Jari', 23),
('Jóia', 23),
('Júlio de Castilhos', 23),
('Lagoa Bonita do Sul', 23),
('Lagoa dos Três Cantos', 23),
('Lagoa Vermelha', 23),
('Lagoão', 23),
('Lajeado', 23),
('Lajeado do Bugre', 23),
('Lavras do Sul', 23),
('Liberato Salzano', 23),
('Lindolfo Collor', 23),
('Linha Nova', 23),
('Maçambara', 23),
('Machadinho', 23),
('Mampituba', 23),
('Manoel Viana', 23),
('Maquiné', 23),
('Maratá', 23),
('Marau', 23),
('Marcelino Ramos', 23),
('Mariana Pimentel', 23),
('Mariano Moro', 23),
('Marques de Souza', 23),
('Mata', 23),
('Mato Castelhano', 23),
('Mato Leitão', 23),
('Mato Queimado', 23),
('Maximiliano de Almeida', 23),
('Minas do Leão', 23),
('Miraguaí', 23),
('Montauri', 23),
('Monte Alegre dos Campos', 23),
('Monte Belo do Sul', 23),
('Montenegro', 23),
('Mormaço', 23),
('Morrinhos do Sul', 23),
('Morro Redondo', 23),
('Morro Reuter', 23),
('Mostardas', 23),
('Muçum', 23),
('Muitos Capões', 23),
('Muliterno', 23),
('Não-Me-Toque', 23),
('Nicolau Vergueiro', 23),
('Nonoai', 23),
('Nova Alvorada', 23),
('Nova Araçá', 23),
('Nova Bassano', 23),
('Nova Boa Vista', 23),
('Nova Bréscia', 23),
('Nova Candelária', 23),
('Nova Esperança do Sul', 23),
('Nova Hartz', 23),
('Nova Pádua', 23),
('Nova Palma', 23),
('Nova Petrópolis', 23),
('Nova Prata', 23),
('Nova Ramada', 23),
('Nova Roma do Sul', 23),
('Nova Santa Rita', 23),
('Novo Barreiro', 23),
('Novo Cabrais', 23),
('Novo Hamburgo', 23),
('Novo Machado', 23),
('Novo Tiradentes', 23),
('Novo Xingu', 23),
('Osório', 23),
('Paim Filho', 23),
('Palmares do Sul', 23),
('Palmeira das Missões', 23),
('Palmitinho', 23),
('Panambi', 23),
('Pantano Grande', 23),
('Paraí', 23),
('Paraíso do Sul', 23),
('Pareci Novo', 23),
('Parobé', 23),
('Passa Sete', 23),
('Passo do Sobrado', 23),
('Passo Fundo', 23),
('Paulo Bento', 23),
('Paverama', 23),
('Pedras Altas', 23),
('Pedro Osório', 23),
('Pejuçara', 23),
('Pelotas', 23),
('Picada Café', 23),
('Pinhal', 23),
('Pinhal da Serra', 23),
('Pinhal Grande', 23),
('Pinheirinho do Vale', 23),
('Pinheiro Machado', 23),
('Pirapó', 23),
('Piratini', 23),
('Planalto', 23),
('Poço das Antas', 23),
('Pontão', 23),
('Ponte Preta', 23),
('Portão', 23),
('Porto Alegre', 23),
('Porto Lucena', 23),
('Porto Mauá', 23),
('Porto Vera Cruz', 23),
('Porto Xavier', 23),
('Pouso Novo', 23),
('Presidente Lucena', 23),
('Progresso', 23),
('Protásio Alves', 23),
('Putinga', 23),
('Quaraí', 23),
('Quatro Irmãos', 23),
('Quevedos', 23),
('Quinze de Novembro', 23),
('Redentora', 23),
('Relvado', 23),
('Restinga Seca', 23),
('Rio dos Índios', 23),
('Rio Grande', 23),
('Rio Pardo', 23),
('Riozinho', 23),
('Roca Sales', 23),
('Rodeio Bonito', 23),
('Rolador', 23),
('Rolante', 23),
('Ronda Alta', 23),
('Rondinha', 23),
('Roque Gonzales', 23),
('Rosário do Sul', 23),
('Sagrada Família', 23),
('Saldanha Marinho', 23),
('Salto do Jacuí', 23),
('Salvador das Missões', 23),
('Salvador do Sul', 23),
('Sananduva', 23),
('Santa Bárbara do Sul', 23),
('Santa Cecília do Sul', 23),
('Santa Clara do Sul', 23),
('Santa Cruz do Sul', 23),
('Santa Margarida do Sul', 23),
('Santa Maria', 23),
('Santa Maria do Herval', 23),
('Santa Rosa', 23),
('Santa Tereza', 23),
('Santa Vitória do Palmar', 23),
('Santana da Boa Vista', 23),
('Santana do Livramento', 23),
('Santiago', 23),
('Santo Ângelo', 23),
('Santo Antônio da Patrulha', 23),
('Santo Antônio das Missões', 23),
('Santo Antônio do Palma', 23),
('Santo Antônio do Planalto', 23),
('Santo Augusto', 23),
('Santo Cristo', 23),
('Santo Expedito do Sul', 23),
('São Borja', 23),
('São Domingos do Sul', 23),
('São Francisco de Assis', 23),
('São Francisco de Paula', 23),
('São Gabriel', 23),
('São Jerônimo', 23),
('São João da Urtiga', 23),
('São João do Polêsine', 23),
('São Jorge', 23),
('São José das Missões', 23),
('São José do Herval', 23),
('São José do Hortêncio', 23),
('São José do Inhacorá', 23),
('São José do Norte', 23),
('São José do Ouro', 23),
('São José do Sul', 23),
('São José dos Ausentes', 23),
('São Leopoldo', 23),
('São Lourenço do Sul', 23),
('São Luiz Gonzaga', 23),
('São Marcos', 23),
('São Martinho', 23),
('São Martinho da Serra', 23),
('São Miguel das Missões', 23),
('São Nicolau', 23),
('São Paulo das Missões', 23),
('São Pedro da Serra', 23),
('São Pedro das Missões', 23),
('São Pedro do Butiá', 23),
('São Pedro do Sul', 23),
('São Sebastião do Caí', 23),
('São Sepé', 23),
('São Valentim', 23),
('São Valentim do Sul', 23),
('São Valério do Sul', 23),
('São Vendelino', 23),
('São Vicente do Sul', 23),
('Sapiranga', 23),
('Sapucaia do Sul', 23),
('Sarandi', 23),
('Seberi', 23),
('Sede Nova', 23),
('Segredo', 23),
('Selbach', 23),
('Senador Salgado Filho', 23),
('Sentinela do Sul', 23),
('Serafina Corrêa', 23),
('Sério', 23),
('Sertão', 23),
('Sertão Santana', 23),
('Sete de Setembro', 23),
('Severiano de Almeida', 23),
('Silveira Martins', 23),
('Sinimbu', 23),
('Sobradinho', 23),
('Soledade', 23),
('Tabaí', 23),
('Tapejara', 23),
('Tapera', 23),
('Tapes', 23),
('Taquara', 23),
('Taquari', 23),
('Taquaruçu do Sul', 23),
('Tavares', 23),
('Tenente Portela', 23),
('Terra de Areia', 23),
('Teutônia', 23),
('Tio Hugo', 23),
('Tiradentes do Sul', 23),
('Toropi', 23),
('Torres', 23),
('Tramandaí', 23),
('Travesseiro', 23),
('Três Arroios', 23),
('Três Cachoeiras', 23),
('Três Coroas', 23),
('Três de Maio', 23),
('Três Forquilhas', 23),
('Três Palmeiras', 23),
('Três Passos', 23),
('Trindade do Sul', 23),
('Triunfo', 23),
('Tucunduva', 23),
('Tunas', 23),
('Tupanci do Sul', 23),
('Tupanciretã', 23),
('Tupandi', 23),
('Tuparendi', 23),
('Turuçu', 23),
('Ubiretama', 23),
('União da Serra', 23),
('Unistalda', 23),
('Uruguaiana', 23),
('Vacaria', 23),
('Vale do Sol', 23),
('Vale Real', 23),
('Vale Verde', 23),
('Vanini', 23),
('Venâncio Aires', 23),
('Vera Cruz', 23),
('Veranópolis', 23),
('Vespasiano Correa', 23),
('Viadutos', 23),
('Viamão', 23),
('Vicente Dutra', 23),
('Victor Graeff', 23),
('Vila Flores', 23),
('Vila Lângaro', 23),
('Vila Maria', 23),
('Vila Nova do Sul', 23),
('Vista Alegre', 23),
('Vista Alegre do Prata', 23),
('Vista Gaúcha', 23),
('Vitória das Missões', 23),
('Westfália', 23),
('Xangri-lá', 23),
('Alta Floresta d`Oeste', 21),
('Alto Alegre dos Parecis', 21),
('Alto Paraíso', 21),
('Alvorada d`Oeste', 21),
('Ariquemes', 21),
('Buritis', 21),
('Cabixi', 21),
('Cacaulândia', 21),
('Cacoal', 21),
('Campo Novo de Rondônia', 21),
('Candeias do Jamari', 21),
('Castanheiras', 21),
('Cerejeiras', 21),
('Chupinguaia', 21),
('Colorado do Oeste', 21),
('Corumbiara', 21),
('Costa Marques', 21),
('Cujubim', 21),
('Espigão d`Oeste', 21),
('Governador Jorge Teixeira', 21),
('Guajará-Mirim', 21),
('Itapuã do Oeste', 21),
('Jaru', 21),
('Ji-Paraná', 21),
('Machadinho d`Oeste', 21),
('Ministro Andreazza', 21),
('Mirante da Serra', 21),
('Monte Negro', 21),
('Nova Brasilândia d`Oeste', 21),
('Nova Mamoré', 21),
('Nova União', 21),
('Novo Horizonte do Oeste', 21),
('Ouro Preto do Oeste', 21),
('Parecis', 21),
('Pimenta Bueno', 21),
('Pimenteiras do Oeste', 21),
('Porto Velho', 21),
('Presidente Médici', 21),
('Primavera de Rondônia', 21),
('Rio Crespo', 21),
('Rolim de Moura', 21),
('Santa Luzia d`Oeste', 21),
('São Felipe d`Oeste', 21),
('São Francisco do Guaporé', 21),
('São Miguel do Guaporé', 21),
('Seringueiras', 21),
('Teixeirópolis', 21),
('Theobroma', 21),
('Urupá', 21),
('Vale do Anari', 21),
('Vale do Paraíso', 21),
('Vilhena', 21),
('Alto Alegre', 22),
('Amajari', 22),
('Boa Vista', 22),
('Bonfim', 22),
('Cantá', 22),
('Caracaraí', 22),
('Caroebe', 22),
('Iracema', 22),
('Mucajaí', 22),
('Normandia', 22),
('Pacaraima', 22),
('Rorainópolis', 22),
('São João da Baliza', 22),
('São Luiz', 22),
('Uiramutã', 22),
('Abdon Batista', 24),
('Abelardo Luz', 24),
('Agrolândia', 24),
('Agronômica', 24),
('Água Doce', 24),
('Águas de Chapecó', 24),
('Águas Frias', 24),
('Águas Mornas', 24),
('Alfredo Wagner', 24),
('Alto Bela Vista', 24),
('Anchieta', 24),
('Angelina', 24),
('Anita Garibaldi', 24),
('Anitápolis', 24),
('Antônio Carlos', 24),
('Apiúna', 24),
('Arabutã', 24),
('Araquari', 24),
('Araranguá', 24),
('Armazém', 24),
('Arroio Trinta', 24),
('Arvoredo', 24),
('Ascurra', 24),
('Atalanta', 24),
('Aurora', 24),
('Balneário Arroio do Silva', 24),
('Balneário Barra do Sul', 24),
('Balneário Camboriú', 24),
('Balneário Gaivota', 24),
('Bandeirante', 24),
('Barra Bonita', 24),
('Barra Velha', 24),
('Bela Vista do Toldo', 24),
('Belmonte', 24),
('Benedito Novo', 24),
('Biguaçu', 24),
('Blumenau', 24),
('Bocaina do Sul', 24),
('Bom Jardim da Serra', 24),
('Bom Jesus', 24),
('Bom Jesus do Oeste', 24),
('Bom Retiro', 24),
('Bombinhas', 24),
('Botuverá', 24),
('Braço do Norte', 24),
('Braço do Trombudo', 24),
('Brunópolis', 24),
('Brusque', 24),
('Caçador', 24),
('Caibi', 24),
('Calmon', 24),
('Camboriú', 24),
('Campo Alegre', 24),
('Campo Belo do Sul', 24),
('Campo Erê', 24),
('Campos Novos', 24),
('Canelinha', 24),
('Canoinhas', 24),
('Capão Alto', 24),
('Capinzal', 24),
('Capivari de Baixo', 24),
('Catanduvas', 24),
('Caxambu do Sul', 24),
('Celso Ramos', 24),
('Cerro Negro', 24),
('Chapadão do Lageado', 24),
('Chapecó', 24),
('Cocal do Sul', 24),
('Concórdia', 24),
('Cordilheira Alta', 24),
('Coronel Freitas', 24),
('Coronel Martins', 24),
('Correia Pinto', 24),
('Corupá', 24),
('Criciúma', 24),
('Cunha Porã', 24),
('Cunhataí', 24),
('Curitibanos', 24),
('Descanso', 24),
('Dionísio Cerqueira', 24),
('Dona Emma', 24),
('Doutor Pedrinho', 24),
('Entre Rios', 24),
('Ermo', 24),
('Erval Velho', 24),
('Faxinal dos Guedes', 24),
('Flor do Sertão', 24),
('Florianópolis', 24),
('Formosa do Sul', 24),
('Forquilhinha', 24),
('Fraiburgo', 24),
('Frei Rogério', 24),
('Galvão', 24),
('Garopaba', 24),
('Garuva', 24),
('Gaspar', 24),
('Governador Celso Ramos', 24),
('Grão Pará', 24),
('Gravatal', 24),
('Guabiruba', 24),
('Guaraciaba', 24),
('Guaramirim', 24),
('Guarujá do Sul', 24),
('Guatambú', 24),
('Herval d`Oeste', 24),
('Ibiam', 24),
('Ibicaré', 24),
('Ibirama', 24),
('Içara', 24),
('Ilhota', 24),
('Imaruí', 24),
('Imbituba', 24),
('Imbuia', 24),
('Indaial', 24),
('Iomerê', 24),
('Ipira', 24),
('Iporã do Oeste', 24),
('Ipuaçu', 24),
('Ipumirim', 24),
('Iraceminha', 24),
('Irani', 24),
('Irati', 24),
('Irineópolis', 24),
('Itá', 24),
('Itaiópolis', 24),
('Itajaí', 24),
('Itapema', 24),
('Itapiranga', 24),
('Itapoá', 24),
('Ituporanga', 24),
('Jaborá', 24),
('Jacinto Machado', 24),
('Jaguaruna', 24),
('Jaraguá do Sul', 24),
('Jardinópolis', 24),
('Joaçaba', 24),
('Joinville', 24),
('José Boiteux', 24),
('Jupiá', 24),
('Lacerdópolis', 24),
('Lages', 24),
('Laguna', 24),
('Lajeado Grande', 24),
('Laurentino', 24),
('Lauro Muller', 24),
('Lebon Régis', 24),
('Leoberto Leal', 24),
('Lindóia do Sul', 24),
('Lontras', 24),
('Luiz Alves', 24),
('Luzerna', 24),
('Macieira', 24),
('Mafra', 24),
('Major Gercino', 24),
('Major Vieira', 24),
('Maracajá', 24),
('Maravilha', 24),
('Marema', 24),
('Massaranduba', 24),
('Matos Costa', 24),
('Meleiro', 24),
('Mirim Doce', 24),
('Modelo', 24),
('Mondaí', 24),
('Monte Carlo', 24),
('Monte Castelo', 24),
('Morro da Fumaça', 24),
('Morro Grande', 24),
('Navegantes', 24),
('Nova Erechim', 24),
('Nova Itaberaba', 24),
('Nova Trento', 24),
('Nova Veneza', 24),
('Novo Horizonte', 24),
('Orleans', 24),
('Otacílio Costa', 24),
('Ouro', 24),
('Ouro Verde', 24),
('Paial', 24),
('Painel', 24),
('Palhoça', 24),
('Palma Sola', 24),
('Palmeira', 24),
('Palmitos', 24),
('Papanduva', 24),
('Paraíso', 24),
('Passo de Torres', 24),
('Passos Maia', 24),
('Paulo Lopes', 24),
('Pedras Grandes', 24),
('Penha', 24),
('Peritiba', 24),
('Petrolândia', 24),
('Piçarras', 24),
('Pinhalzinho', 24),
('Pinheiro Preto', 24),
('Piratuba', 24),
('Planalto Alegre', 24),
('Pomerode', 24),
('Ponte Alta', 24),
('Ponte Alta do Norte', 24),
('Ponte Serrada', 24),
('Porto Belo', 24),
('Porto União', 24),
('Pouso Redondo', 24),
('Praia Grande', 24),
('Presidente Castelo Branco', 24),
('Presidente Getúlio', 24),
('Presidente Nereu', 24),
('Princesa', 24),
('Quilombo', 24),
('Rancho Queimado', 24),
('Rio das Antas', 24),
('Rio do Campo', 24),
('Rio do Oeste', 24),
('Rio do Sul', 24),
('Rio dos Cedros', 24),
('Rio Fortuna', 24),
('Rio Negrinho', 24),
('Rio Rufino', 24),
('Riqueza', 24),
('Rodeio', 24),
('Romelândia', 24),
('Salete', 24),
('Saltinho', 24),
('Salto Veloso', 24),
('Sangão', 24),
('Santa Cecília', 24),
('Santa Helena', 24),
('Santa Rosa de Lima', 24),
('Santa Rosa do Sul', 24),
('Santa Terezinha', 24),
('Santa Terezinha do Progresso', 24),
('Santiago do Sul', 24),
('Santo Amaro da Imperatriz', 24),
('São Bento do Sul', 24),
('São Bernardino', 24),
('São Bonifácio', 24),
('São Carlos', 24),
('São Cristovão do Sul', 24),
('São Domingos', 24),
('São Francisco do Sul', 24),
('São João Batista', 24),
('São João do Itaperiú', 24),
('São João do Oeste', 24),
('São João do Sul', 24),
('São Joaquim', 24),
('São José', 24),
('São José do Cedro', 24),
('São José do Cerrito', 24),
('São Lourenço do Oeste', 24),
('São Ludgero', 24),
('São Martinho', 24),
('São Miguel da Boa Vista', 24),
('São Miguel do Oeste', 24),
('São Pedro de Alcântara', 24),
('Saudades', 24),
('Schroeder', 24),
('Seara', 24),
('Serra Alta', 24),
('Siderópolis', 24),
('Sombrio', 24),
('Sul Brasil', 24),
('Taió', 24),
('Tangará', 24),
('Tigrinhos', 24),
('Tijucas', 24),
('Timbé do Sul', 24),
('Timbó', 24),
('Timbó Grande', 24),
('Três Barras', 24),
('Treviso', 24),
('Treze de Maio', 24),
('Treze Tílias', 24),
('Trombudo Central', 24),
('Tubarão', 24),
('Tunápolis', 24),
('Turvo', 24),
('União do Oeste', 24),
('Urubici', 24),
('Urupema', 24),
('Urussanga', 24),
('Vargeão', 24),
('Vargem', 24),
('Vargem Bonita', 24),
('Vidal Ramos', 24),
('Videira', 24),
('Vitor Meireles', 24),
('Witmarsum', 24),
('Xanxerê', 24),
('Xavantina', 24),
('Xaxim', 24),
('Zortéa', 24),
('Adamantina', 26),
('Adolfo', 26),
('Aguaí', 26),
('Águas da Prata', 26),
('Águas de Lindóia', 26),
('Águas de Santa Bárbara', 26),
('Águas de São Pedro', 26),
('Agudos', 26),
('Alambari', 26),
('Alfredo Marcondes', 26),
('Altair', 26),
('Altinópolis', 26),
('Alto Alegre', 26),
('Alumínio', 26),
('Álvares Florence', 26),
('Álvares Machado', 26),
('Álvaro de Carvalho', 26),
('Alvinlândia', 26),
('Americana', 26),
('Américo Brasiliense', 26),
('Américo de Campos', 26),
('Amparo', 26),
('Analândia', 26),
('Andradina', 26),
('Angatuba', 26),
('Anhembi', 26),
('Anhumas', 26),
('Aparecida', 26),
('Aparecida d`Oeste', 26),
('Apiaí', 26),
('Araçariguama', 26),
('Araçatuba', 26),
('Araçoiaba da Serra', 26),
('Aramina', 26),
('Arandu', 26),
('Arapeí', 26),
('Araraquara', 26),
('Araras', 26),
('Arco-Íris', 26),
('Arealva', 26),
('Areias', 26),
('Areiópolis', 26),
('Ariranha', 26),
('Artur Nogueira', 26),
('Arujá', 26),
('Aspásia', 26),
('Assis', 26),
('Atibaia', 26),
('Auriflama', 26),
('Avaí', 26),
('Avanhandava', 26),
('Avaré', 26),
('Bady Bassitt', 26),
('Balbinos', 26),
('Bálsamo', 26),
('Bananal', 26),
('Barão de Antonina', 26),
('Barbosa', 26),
('Bariri', 26),
('Barra Bonita', 26),
('Barra do Chapéu', 26),
('Barra do Turvo', 26),
('Barretos', 26),
('Barrinha', 26),
('Barueri', 26),
('Bastos', 26),
('Batatais', 26),
('Bauru', 26),
('Bebedouro', 26),
('Bento de Abreu', 26),
('Bernardino de Campos', 26),
('Bertioga', 26),
('Bilac', 26),
('Birigui', 26),
('Biritiba-Mirim', 26),
('Boa Esperança do Sul', 26),
('Bocaina', 26),
('Bofete', 26),
('Boituva', 26),
('Bom Jesus dos Perdões', 26),
('Bom Sucesso de Itararé', 26),
('Borá', 26),
('Boracéia', 26),
('Borborema', 26),
('Borebi', 26),
('Botucatu', 26),
('Bragança Paulista', 26),
('Braúna', 26),
('Brejo Alegre', 26),
('Brodowski', 26),
('Brotas', 26),
('Buri', 26),
('Buritama', 26),
('Buritizal', 26),
('Cabrália Paulista', 26),
('Cabreúva', 26),
('Caçapava', 26),
('Cachoeira Paulista', 26),
('Caconde', 26),
('Cafelândia', 26),
('Caiabu', 26),
('Caieiras', 26),
('Caiuá', 26),
('Cajamar', 26),
('Cajati', 26),
('Cajobi', 26),
('Cajuru', 26),
('Campina do Monte Alegre', 26),
('Campinas', 26),
('Campo Limpo Paulista', 26),
('Campos do Jordão', 26),
('Campos Novos Paulista', 26),
('Cananéia', 26),
('Canas', 26),
('Cândido Mota', 26),
('Cândido Rodrigues', 26),
('Canitar', 26),
('Capão Bonito', 26),
('Capela do Alto', 26),
('Capivari', 26),
('Caraguatatuba', 26),
('Carapicuíba', 26),
('Cardoso', 26),
('Casa Branca', 26),
('Cássia dos Coqueiros', 26),
('Castilho', 26),
('Catanduva', 26),
('Catiguá', 26),
('Cedral', 26),
('Cerqueira César', 26),
('Cerquilho', 26),
('Cesário Lange', 26),
('Charqueada', 26),
('Chavantes', 26),
('Clementina', 26),
('Colina', 26),
('Colômbia', 26),
('Conchal', 26),
('Conchas', 26),
('Cordeirópolis', 26),
('Coroados', 26),
('Coronel Macedo', 26),
('Corumbataí', 26),
('Cosmópolis', 26),
('Cosmorama', 26),
('Cotia', 26),
('Cravinhos', 26),
('Cristais Paulista', 26),
('Cruzália', 26),
('Cruzeiro', 26),
('Cubatão', 26),
('Cunha', 26),
('Descalvado', 26),
('Diadema', 26),
('Dirce Reis', 26),
('Divinolândia', 26),
('Dobrada', 26),
('Dois Córregos', 26),
('Dolcinópolis', 26),
('Dourado', 26),
('Dracena', 26),
('Duartina', 26),
('Dumont', 26),
('Echaporã', 26),
('Eldorado', 26),
('Elias Fausto', 26),
('Elisiário', 26),
('Embaúba', 26),
('Embu', 26),
('Embu-Guaçu', 26),
('Emilianópolis', 26),
('Engenheiro Coelho', 26),
('Espírito Santo do Pinhal', 26),
('Espírito Santo do Turvo', 26),
('Estiva Gerbi', 26),
('Estrela d`Oeste', 26),
('Estrela do Norte', 26),
('Euclides da Cunha Paulista', 26),
('Fartura', 26),
('Fernando Prestes', 26),
('Fernandópolis', 26),
('Fernão', 26),
('Ferraz de Vasconcelos', 26),
('Flora Rica', 26),
('Floreal', 26),
('Flórida Paulista', 26),
('Florínia', 26),
('Franca', 26),
('Francisco Morato', 26),
('Franco da Rocha', 26),
('Gabriel Monteiro', 26),
('Gália', 26),
('Garça', 26),
('Gastão Vidigal', 26),
('Gavião Peixoto', 26),
('General Salgado', 26),
('Getulina', 26),
('Glicério', 26),
('Guaiçara', 26),
('Guaimbê', 26),
('Guaíra', 26),
('Guapiaçu', 26),
('Guapiara', 26),
('Guará', 26),
('Guaraçaí', 26),
('Guaraci', 26),
('Guarani d`Oeste', 26),
('Guarantã', 26),
('Guararapes', 26),
('Guararema', 26),
('Guaratinguetá', 26),
('Guareí', 26),
('Guariba', 26),
('Guarujá', 26),
('Guarulhos', 26),
('Guatapará', 26),
('Guzolândia', 26),
('Herculândia', 26),
('Holambra', 26),
('Hortolândia', 26),
('Iacanga', 26),
('Iacri', 26),
('Iaras', 26),
('Ibaté', 26),
('Ibirá', 26),
('Ibirarema', 26),
('Ibitinga', 26),
('Ibiúna', 26),
('Icém', 26),
('Iepê', 26),
('Igaraçu do Tietê', 26),
('Igarapava', 26),
('Igaratá', 26),
('Iguape', 26),
('Ilha Comprida', 26),
('Ilha Solteira', 26),
('Ilhabela', 26),
('Indaiatuba', 26),
('Indiana', 26),
('Indiaporã', 26),
('Inúbia Paulista', 26),
('Ipaussu', 26),
('Iperó', 26),
('Ipeúna', 26),
('Ipiguá', 26),
('Iporanga', 26),
('Ipuã', 26),
('Iracemápolis', 26),
('Irapuã', 26),
('Irapuru', 26),
('Itaberá', 26),
('Itaí', 26),
('Itajobi', 26),
('Itaju', 26),
('Itanhaém', 26),
('Itaóca', 26),
('Itapecerica da Serra', 26),
('Itapetininga', 26),
('Itapeva', 26),
('Itapevi', 26),
('Itapira', 26),
('Itapirapuã Paulista', 26),
('Itápolis', 26),
('Itaporanga', 26),
('Itapuí', 26),
('Itapura', 26),
('Itaquaquecetuba', 26),
('Itararé', 26),
('Itariri', 26),
('Itatiba', 26),
('Itatinga', 26),
('Itirapina', 26),
('Itirapuã', 26),
('Itobi', 26),
('Itu', 26),
('Itupeva', 26),
('Ituverava', 26),
('Jaborandi', 26),
('Jaboticabal', 26),
('Jacareí', 26),
('Jaci', 26),
('Jacupiranga', 26),
('Jaguariúna', 26),
('Jales', 26),
('Jambeiro', 26),
('Jandira', 26),
('Jardinópolis', 26);