/*
USE colorcommercedb;
*/
INSERT INTO cidade (ci_nome, ci_es_cod) VALUES
('Itaguaru', 9),
('Itajá', 9),
('Itapaci', 9),
('Itapirapuã', 9),
('Itapuranga', 9),
('Itarumã', 9),
('Itauçu', 9),
('Itumbiara', 9),
('Ivolândia', 9),
('Jandaia', 9),
('Jaraguá', 9),
('Jataí', 9),
('Jaupaci', 9),
('Jesúpolis', 9),
('Joviânia', 9),
('Jussara', 9),
('Lagoa Santa', 9),
('Leopoldo de Bulhões', 9),
('Luziânia', 9),
('Mairipotaba', 9),
('Mambaí', 9),
('Mara Rosa', 9),
('Marzagão', 9),
('Matrinchã', 9),
('Maurilândia', 9),
('Mimoso de Goiás', 9),
('Minaçu', 9),
('Mineiros', 9),
('Moiporá', 9),
('Monte Alegre de Goiás', 9),
('Montes Claros de Goiás', 9),
('Montividiu', 9),
('Montividiu do Norte', 9),
('Morrinhos', 9),
('Morro Agudo de Goiás', 9),
('Mossâmedes', 9),
('Mozarlândia', 9),
('Mundo Novo', 9),
('Mutunópolis', 9),
('Nazário', 9),
('Nerópolis', 9),
('Niquelândia', 9),
('Nova América', 9),
('Nova Aurora', 9),
('Nova Crixás', 9),
('Nova Glória', 9),
('Nova Iguaçu de Goiás', 9),
('Nova Roma', 9),
('Nova Veneza', 9),
('Novo Brasil', 9),
('Novo Gama', 9),
('Novo Planalto', 9),
('Orizona', 9),
('Ouro Verde de Goiás', 9),
('Ouvidor', 9),
('Padre Bernardo', 9),
('Palestina de Goiás', 9),
('Palmeiras de Goiás', 9),
('Palmelo', 9),
('Palminópolis', 9),
('Panamá', 9),
('Paranaiguara', 9),
('Paraúna', 9),
('Perolândia', 9),
('Petrolina de Goiás', 9),
('Pilar de Goiás', 9),
('Piracanjuba', 9),
('Piranhas', 9),
('Pirenópolis', 9),
('Pires do Rio', 9),
('Planaltina', 9),
('Pontalina', 9),
('Porangatu', 9),
('Porteirão', 9),
('Portelândia', 9),
('Posse', 9),
('Professor Jamil', 9),
('Quirinópolis', 9),
('Rialma', 9),
('Rianápolis', 9),
('Rio Quente', 9),
('Rio Verde', 9),
('Rubiataba', 9),
('Sanclerlândia', 9),
('Santa Bárbara de Goiás', 9),
('Santa Cruz de Goiás', 9),
('Santa Fé de Goiás', 9),
('Santa Helena de Goiás', 9),
('Santa Isabel', 9),
('Santa Rita do Araguaia', 9),
('Santa Rita do Novo Destino', 9),
('Santa Rosa de Goiás', 9),
('Santa Tereza de Goiás', 9),
('Santa Terezinha de Goiás', 9),
('Santo Antônio da Barra', 9),
('Santo Antônio de Goiás', 9),
('Santo Antônio do Descoberto', 9),
('São Domingos', 9),
('São Francisco de Goiás', 9),
('São João d`Aliança', 9),
('São João da Paraúna', 9),
('São Luís de Montes Belos', 9),
('São Luíz do Norte', 9),
('São Miguel do Araguaia', 9),
('São Miguel do Passa Quatro', 9),
('São Patrício', 9),
('São Simão', 9),
('Senador Canedo', 9),
('Serranópolis', 9),
('Silvânia', 9),
('Simolândia', 9),
('Sítio d`Abadia', 9),
('Taquaral de Goiás', 9),
('Teresina de Goiás', 9),
('Terezópolis de Goiás', 9),
('Três Ranchos', 9),
('Trindade', 9),
('Trombas', 9),
('Turvânia', 9),
('Turvelândia', 9),
('Uirapuru', 9),
('Uruaçu', 9),
('Uruana', 9),
('Urutaí', 9),
('Valparaíso de Goiás', 9),
('Varjão', 9),
('Vianópolis', 9),
('Vicentinópolis', 9),
('Vila Boa', 9),
('Vila Propício', 9),
('Açailândia', 10),
('Afonso Cunha', 10),
('Água Doce do Maranhão', 10),
('Alcântara', 10),
('Aldeias Altas', 10),
('Altamira do Maranhão', 10),
('Alto Alegre do Maranhão', 10),
('Alto Alegre do Pindaré', 10),
('Alto Parnaíba', 10),
('Amapá do Maranhão', 10),
('Amarante do Maranhão', 10),
('Anajatuba', 10),
('Anapurus', 10),
('Apicum-Açu', 10),
('Araguanã', 10),
('Araioses', 10),
('Arame', 10),
('Arari', 10),
('Axixá', 10),
('Bacabal', 10),
('Bacabeira', 10),
('Bacuri', 10),
('Bacurituba', 10),
('Balsas', 10),
('Barão de Grajaú', 10),
('Barra do Corda', 10),
('Barreirinhas', 10),
('Bela Vista do Maranhão', 10),
('Belágua', 10),
('Benedito Leite', 10),
('Bequimão', 10),
('Bernardo do Mearim', 10),
('Boa Vista do Gurupi', 10),
('Bom Jardim', 10),
('Bom Jesus das Selvas', 10),
('Bom Lugar', 10),
('Brejo', 10),
('Brejo de Areia', 10),
('Buriti', 10),
('Buriti Bravo', 10),
('Buriticupu', 10),
('Buritirana', 10),
('Cachoeira Grande', 10),
('Cajapió', 10),
('Cajari', 10),
('Campestre do Maranhão', 10),
('Cândido Mendes', 10),
('Cantanhede', 10),
('Capinzal do Norte', 10),
('Carolina', 10),
('Carutapera', 10),
('Caxias', 10),
('Cedral', 10),
('Central do Maranhão', 10),
('Centro do Guilherme', 10),
('Centro Novo do Maranhão', 10),
('Chapadinha', 10),
('Cidelândia', 10),
('Codó', 10),
('Coelho Neto', 10),
('Colinas', 10),
('Conceição do Lago-Açu', 10),
('Coroatá', 10),
('Cururupu', 10),
('Davinópolis', 10),
('Dom Pedro', 10),
('Duque Bacelar', 10),
('Esperantinópolis', 10),
('Estreito', 10),
('Feira Nova do Maranhão', 10),
('Fernando Falcão', 10),
('Formosa da Serra Negra', 10),
('Fortaleza dos Nogueiras', 10),
('Fortuna', 10),
('Godofredo Viana', 10),
('Gonçalves Dias', 10),
('Governador Archer', 10),
('Governador Edison Lobão', 10),
('Governador Eugênio Barros', 10),
('Governador Luiz Rocha', 10),
('Governador Newton Bello', 10),
('Governador Nunes Freire', 10),
('Graça Aranha', 10),
('Grajaú', 10),
('Guimarães', 10),
('Humberto de Campos', 10),
('Icatu', 10),
('Igarapé do Meio', 10),
('Igarapé Grande', 10),
('Imperatriz', 10),
('Itaipava do Grajaú', 10),
('Itapecuru Mirim', 10),
('Itinga do Maranhão', 10),
('Jatobá', 10),
('Jenipapo dos Vieiras', 10),
('João Lisboa', 10),
('Joselândia', 10),
('Junco do Maranhão', 10),
('Lago da Pedra', 10),
('Lago do Junco', 10),
('Lago dos Rodrigues', 10),
('Lago Verde', 10),
('Lagoa do Mato', 10),
('Lagoa Grande do Maranhão', 10),
('Lajeado Novo', 10),
('Lima Campos', 10),
('Loreto', 10),
('Luís Domingues', 10),
('Magalhães de Almeida', 10),
('Maracaçumé', 10),
('Marajá do Sena', 10),
('Maranhãozinho', 10),
('Mata Roma', 10),
('Matinha', 10),
('Matões', 10),
('Matões do Norte', 10),
('Milagres do Maranhão', 10),
('Mirador', 10),
('Miranda do Norte', 10),
('Mirinzal', 10),
('Monção', 10),
('Montes Altos', 10),
('Morros', 10),
('Nina Rodrigues', 10),
('Nova Colinas', 10),
('Nova Iorque', 10),
('Nova Olinda do Maranhão', 10),
('Olho d`Água das Cunhãs', 10),
('Olinda Nova do Maranhão', 10),
('Paço do Lumiar', 10),
('Palmeirândia', 10),
('Paraibano', 10),
('Parnarama', 10),
('Passagem Franca', 10),
('Pastos Bons', 10),
('Paulino Neves', 10),
('Paulo Ramos', 10),
('Pedreiras', 10),
('Pedro do Rosário', 10),
('Penalva', 10),
('Peri Mirim', 10),
('Peritoró', 10),
('Pindaré-Mirim', 10),
('Pinheiro', 10),
('Pio XII', 10),
('Pirapemas', 10),
('Poção de Pedras', 10),
('Porto Franco', 10),
('Porto Rico do Maranhão', 10),
('Presidente Dutra', 10),
('Presidente Juscelino', 10),
('Presidente Médici', 10),
('Presidente Sarney', 10),
('Presidente Vargas', 10),
('Primeira Cruz', 10),
('Raposa', 10),
('Riachão', 10),
('Ribamar Fiquene', 10),
('Rosário', 10),
('Sambaíba', 10),
('Santa Filomena do Maranhão', 10),
('Santa Helena', 10),
('Santa Inês', 10),
('Santa Luzia', 10),
('Santa Luzia do Paruá', 10),
('Santa Quitéria do Maranhão', 10),
('Santa Rita', 10),
('Santana do Maranhão', 10),
('Santo Amaro do Maranhão', 10),
('Santo Antônio dos Lopes', 10),
('São Benedito do Rio Preto', 10),
('São Bento', 10),
('São Bernardo', 10),
('São Domingos do Azeitão', 10),
('São Domingos do Maranhão', 10),
('São Félix de Balsas', 10),
('São Francisco do Brejão', 10),
('São Francisco do Maranhão', 10),
('São João Batista', 10),
('São João do Carú', 10),
('São João do Paraíso', 10),
('São João do Soter', 10),
('São João dos Patos', 10),
('São José de Ribamar', 10),
('São José dos Basílios', 10),
('São Luís', 10),
('São Luís Gonzaga do Maranhão', 10),
('São Mateus do Maranhão', 10),
('São Pedro da Água Branca', 10),
('São Pedro dos Crentes', 10),
('São Raimundo das Mangabeiras', 10),
('São Raimundo do Doca Bezerra', 10),
('São Roberto', 10),
('São Vicente Ferrer', 10),
('Satubinha', 10),
('Senador Alexandre Costa', 10),
('Senador La Rocque', 10),
('Serrano do Maranhão', 10),
('Sítio Novo', 10),
('Sucupira do Norte', 10),
('Sucupira do Riachão', 10),
('Tasso Fragoso', 10),
('Timbiras', 10),
('Timon', 10),
('Trizidela do Vale', 10),
('Tufilândia', 10),
('Tuntum', 10),
('Turiaçu', 10),
('Turilândia', 10),
('Tutóia', 10),
('Urbano Santos', 10),
('Vargem Grande', 10),
('Viana', 10),
('Vila Nova dos Martírios', 10),
('Vitória do Mearim', 10),
('Vitorino Freire', 10),
('Zé Doca', 10),
('Acorizal', 13),
('Água Boa', 13),
('Alta Floresta', 13),
('Alto Araguaia', 13),
('Alto Boa Vista', 13),
('Alto Garças', 13),
('Alto Paraguai', 13),
('Alto Taquari', 13),
('Apiacás', 13),
('Araguaiana', 13),
('Araguainha', 13),
('Araputanga', 13),
('Arenápolis', 13),
('Aripuanã', 13),
('Barão de Melgaço', 13),
('Barra do Bugres', 13),
('Barra do Garças', 13),
('Bom Jesus do Araguaia', 13),
('Brasnorte', 13),
('Cáceres', 13),
('Campinápolis', 13),
('Campo Novo do Parecis', 13),
('Campo Verde', 13),
('Campos de Júlio', 13),
('Canabrava do Norte', 13),
('Canarana', 13),
('Carlinda', 13),
('Castanheira', 13),
('Chapada dos Guimarães', 13),
('Cláudia', 13),
('Cocalinho', 13),
('Colíder', 13),
('Colniza', 13),
('Comodoro', 13),
('Confresa', 13),
('Conquista d`Oeste', 13),
('Cotriguaçu', 13),
('Cuiabá', 13),
('Curvelândia', 13),
('Curvelândia', 13),
('Denise', 13),
('Diamantino', 13),
('Dom Aquino', 13),
('Feliz Natal', 13),
('Figueirópolis d`Oeste', 13),
('Gaúcha do Norte', 13),
('General Carneiro', 13),
('Glória d`Oeste', 13),
('Guarantã do Norte', 13),
('Guiratinga', 13),
('Indiavaí', 13),
('Ipiranga do Norte', 13),
('Itanhangá', 13),
('Itaúba', 13),
('Itiquira', 13),
('Jaciara', 13),
('Jangada', 13),
('Jauru', 13),
('Juara', 13),
('Juína', 13),
('Juruena', 13),
('Juscimeira', 13),
('Lambari d`Oeste', 13),
('Lucas do Rio Verde', 13),
('Luciára', 13),
('Marcelândia', 13),
('Matupá', 13),
('Mirassol d`Oeste', 13),
('Nobres', 13),
('Nortelândia', 13),
('Nossa Senhora do Livramento', 13),
('Nova Bandeirantes', 13),
('Nova Brasilândia', 13),
('Nova Canaã do Norte', 13),
('Nova Guarita', 13),
('Nova Lacerda', 13),
('Nova Marilândia', 13),
('Nova Maringá', 13),
('Nova Monte verde', 13),
('Nova Mutum', 13),
('Nova Olímpia', 13),
('Nova Santa Helena', 13),
('Nova Ubiratã', 13),
('Nova Xavantina', 13),
('Novo Horizonte do Norte', 13),
('Novo Mundo', 13),
('Novo Santo Antônio', 13),
('Novo São Joaquim', 13),
('Paranaíta', 13),
('Paranatinga', 13),
('Pedra Preta', 13),
('Peixoto de Azevedo', 13),
('Planalto da Serra', 13),
('Poconé', 13),
('Pontal do Araguaia', 13),
('Ponte Branca', 13),
('Pontes e Lacerda', 13),
('Porto Alegre do Norte', 13),
('Porto dos Gaúchos', 13),
('Porto Esperidião', 13),
('Porto Estrela', 13),
('Poxoréo', 13),
('Primavera do Leste', 13),
('Querência', 13),
('Reserva do Cabaçal', 13),
('Ribeirão Cascalheira', 13),
('Ribeirãozinho', 13),
('Rio Branco', 13),
('Rondolândia', 13),
('Rondonópolis', 13),
('Rosário Oeste', 13),
('Salto do Céu', 13),
('Santa Carmem', 13),
('Santa Cruz do Xingu', 13),
('Santa Rita do Trivelato', 13),
('Santa Terezinha', 13),
('Santo Afonso', 13),
('Santo Antônio do Leste', 13),
('Santo Antônio do Leverger', 13),
('São Félix do Araguaia', 13),
('São José do Povo', 13),
('São José do Rio Claro', 13),
('São José do Xingu', 13),
('São José dos Quatro Marcos', 13),
('São Pedro da Cipa', 13),
('Sapezal', 13),
('Serra Nova Dourada', 13),
('Sinop', 13),
('Sorriso', 13),
('Tabaporã', 13),
('Tangará da Serra', 13),
('Tapurah', 13),
('Terra Nova do Norte', 13),
('Tesouro', 13),
('Torixoréu', 13),
('União do Sul', 13),
('Vale de São Domingos', 13),
('Várzea Grande', 13),
('Vera', 13),
('Vila Bela da Santíssima Trindade', 13),
('Vila Rica', 13),
('Água Clara', 12),
('Alcinópolis', 12),
('Amambaí', 12),
('Anastácio', 12),
('Anaurilândia', 12),
('Angélica', 12),
('Antônio João', 12),
('Aparecida do Taboado', 12),
('Aquidauana', 12),
('Aral Moreira', 12),
('Bandeirantes', 12),
('Bataguassu', 12),
('Bataiporã', 12),
('Bela Vista', 12),
('Bodoquena', 12),
('Bonito', 12),
('Brasilândia', 12),
('Caarapó', 12),
('Camapuã', 12),
('Campo Grande', 12),
('Caracol', 12),
('Cassilândia', 12),
('Chapadão do Sul', 12),
('Corguinho', 12),
('Coronel Sapucaia', 12),
('Corumbá', 12),
('Costa Rica', 12),
('Coxim', 12),
('Deodápolis', 12),
('Dois Irmãos do Buriti', 12),
('Douradina', 12),
('Dourados', 12),
('Eldorado', 12),
('Fátima do Sul', 12),
('Figueirão', 12),
('Glória de Dourados', 12),
('Guia Lopes da Laguna', 12),
('Iguatemi', 12),
('Inocência', 12),
('Itaporã', 12),
('Itaquiraí', 12),
('Ivinhema', 12),
('Japorã', 12),
('Jaraguari', 12),
('Jardim', 12),
('Jateí', 12),
('Juti', 12),
('Ladário', 12),
('Laguna Carapã', 12),
('Maracaju', 12),
('Miranda', 12),
('Mundo Novo', 12),
('Naviraí', 12),
('Nioaque', 12),
('Nova Alvorada do Sul', 12),
('Nova Andradina', 12),
('Novo Horizonte do Sul', 12),
('Paranaíba', 12),
('Paranhos', 12),
('Pedro Gomes', 12),
('Ponta Porã', 12),
('Porto Murtinho', 12),
('Ribas do Rio Pardo', 12),
('Rio Brilhante', 12),
('Rio Negro', 12),
('Rio Verde de Mato Grosso', 12),
('Rochedo', 12),
('Santa Rita do Pardo', 12),
('São Gabriel do Oeste', 12),
('Selvíria', 12),
('Sete Quedas', 12),
('Sidrolândia', 12),
('Sonora', 12),
('Tacuru', 12),
('Taquarussu', 12),
('Terenos', 12),
('Três Lagoas', 12),
('Vicentina', 12),
('Abadia dos Dourados', 11),
('Abaeté', 11),
('Abre Campo', 11),
('Acaiaca', 11),
('Açucena', 11),
('Água Boa', 11),
('Água Comprida', 11),
('Aguanil', 11),
('Águas Formosas', 11),
('Águas Vermelhas', 11),
('Aimorés', 11),
('Aiuruoca', 11),
('Alagoa', 11),
('Albertina', 11),
('Além Paraíba', 11),
('Alfenas', 11),
('Alfredo Vasconcelos', 11),
('Almenara', 11),
('Alpercata', 11),
('Alpinópolis', 11),
('Alterosa', 11),
('Alto Caparaó', 11),
('Alto Jequitibá', 11),
('Alto Rio Doce', 11),
('Alvarenga', 11),
('Alvinópolis', 11),
('Alvorada de Minas', 11),
('Amparo do Serra', 11),
('Andradas', 11),
('Andrelândia', 11),
('Angelândia', 11),
('Antônio Carlos', 11),
('Antônio Dias', 11),
('Antônio Prado de Minas', 11),
('Araçaí', 11),
('Aracitaba', 11),
('Araçuaí', 11),
('Araguari', 11),
('Arantina', 11),
('Araponga', 11),
('Araporã', 11),
('Arapuá', 11),
('Araújos', 11),
('Araxá', 11),
('Arceburgo', 11),
('Arcos', 11),
('Areado', 11),
('Argirita', 11),
('Aricanduva', 11),
('Arinos', 11),
('Astolfo Dutra', 11),
('Ataléia', 11),
('Augusto de Lima', 11),
('Baependi', 11),
('Baldim', 11),
('Bambuí', 11),
('Bandeira', 11),
('Bandeira do Sul', 11),
('Barão de Cocais', 11),
('Barão de Monte Alto', 11),
('Barbacena', 11),
('Barra Longa', 11),
('Barroso', 11),
('Bela Vista de Minas', 11),
('Belmiro Braga', 11),
('Belo Horizonte', 11),
('Belo Oriente', 11),
('Belo Vale', 11),
('Berilo', 11),
('Berizal', 11),
('Bertópolis', 11),
('Betim', 11),
('Bias Fortes', 11),
('Bicas', 11),
('Biquinhas', 11),
('Boa Esperança', 11),
('Bocaina de Minas', 11),
('Bocaiúva', 11),
('Bom Despacho', 11),
('Bom Jardim de Minas', 11),
('Bom Jesus da Penha', 11),
('Bom Jesus do Amparo', 11),
('Bom Jesus do Galho', 11),
('Bom Repouso', 11),
('Bom Sucesso', 11),
('Bonfim', 11),
('Bonfinópolis de Minas', 11),
('Bonito de Minas', 11),
('Borda da Mata', 11),
('Botelhos', 11),
('Botumirim', 11),
('Brás Pires', 11),
('Brasilândia de Minas', 11),
('Brasília de Minas', 11),
('Brasópolis', 11),
('Braúnas', 11),
('Brumadinho', 11),
('Bueno Brandão', 11),
('Buenópolis', 11),
('Bugre', 11),
('Buritis', 11),
('Buritizeiro', 11),
('Cabeceira Grande', 11),
('Cabo Verde', 11),
('Cachoeira da Prata', 11),
('Cachoeira de Minas', 11),
('Cachoeira de Pajeú', 11),
('Cachoeira Dourada', 11),
('Caetanópolis', 11),
('Caeté', 11),
('Caiana', 11),
('Cajuri', 11),
('Caldas', 11),
('Camacho', 11),
('Camanducaia', 11),
('Cambuí', 11),
('Cambuquira', 11),
('Campanário', 11),
('Campanha', 11),
('Campestre', 11),
('Campina Verde', 11),
('Campo Azul', 11),
('Campo Belo', 11),
('Campo do Meio', 11),
('Campo Florido', 11),
('Campos Altos', 11),
('Campos Gerais', 11),
('Cana Verde', 11),
('Canaã', 11),
('Canápolis', 11),
('Candeias', 11),
('Cantagalo', 11),
('Caparaó', 11),
('Capela Nova', 11),
('Capelinha', 11),
('Capetinga', 11),
('Capim Branco', 11),
('Capinópolis', 11),
('Capitão Andrade', 11),
('Capitão Enéas', 11),
('Capitólio', 11),
('Caputira', 11),
('Caraí', 11),
('Caranaíba', 11),
('Carandaí', 11),
('Carangola', 11),
('Caratinga', 11),
('Carbonita', 11),
('Careaçu', 11),
('Carlos Chagas', 11),
('Carmésia', 11),
('Carmo da Cachoeira', 11),
('Carmo da Mata', 11),
('Carmo de Minas', 11),
('Carmo do Cajuru', 11),
('Carmo do Paranaíba', 11),
('Carmo do Rio Claro', 11),
('Carmópolis de Minas', 11),
('Carneirinho', 11),
('Carrancas', 11),
('Carvalhópolis', 11),
('Carvalhos', 11),
('Casa Grande', 11),
('Cascalho Rico', 11),
('Cássia', 11),
('Cataguases', 11),
('Catas Altas', 11),
('Catas Altas da Noruega', 11),
('Catuji', 11),
('Catuti', 11),
('Caxambu', 11),
('Cedro do Abaeté', 11),
('Central de Minas', 11),
('Centralina', 11),
('Chácara', 11),
('Chalé', 11),
('Chapada do Norte', 11),
('Chapada Gaúcha', 11),
('Chiador', 11),
('Cipotânea', 11),
('Claraval', 11),
('Claro dos Poções', 11),
('Cláudio', 11),
('Coimbra', 11),
('Coluna', 11),
('Comendador Gomes', 11),
('Comercinho', 11),
('Conceição da Aparecida', 11),
('Conceição da Barra de Minas', 11),
('Conceição das Alagoas', 11),
('Conceição das Pedras', 11),
('Conceição de Ipanema', 11),
('Conceição do Mato Dentro', 11),
('Conceição do Pará', 11),
('Conceição do Rio Verde', 11),
('Conceição dos Ouros', 11),
('Cônego Marinho', 11),
('Confins', 11),
('Congonhal', 11),
('Congonhas', 11),
('Congonhas do Norte', 11),
('Conquista', 11),
('Conselheiro Lafaiete', 11),
('Conselheiro Pena', 11),
('Consolação', 11),
('Contagem', 11),
('Coqueiral', 11),
('Coração de Jesus', 11),
('Cordisburgo', 11),
('Cordislândia', 11),
('Corinto', 11),
('Coroaci', 11),
('Coromandel', 11),
('Coronel Fabriciano', 11),
('Coronel Murta', 11),
('Coronel Pacheco', 11),
('Coronel Xavier Chaves', 11),
('Córrego Danta', 11),
('Córrego do Bom Jesus', 11),
('Córrego Fundo', 11),
('Córrego Novo', 11),
('Couto de Magalhães de Minas', 11),
('Crisólita', 11),
('Cristais', 11),
('Cristália', 11),
('Cristiano Otoni', 11),
('Cristina', 11),
('Crucilândia', 11),
('Cruzeiro da Fortaleza', 11),
('Cruzília', 11),
('Cuparaque', 11),
('Curral de Dentro', 11),
('Curvelo', 11),
('Datas', 11),
('Delfim Moreira', 11),
('Delfinópolis', 11),
('Delta', 11),
('Descoberto', 11),
('Desterro de Entre Rios', 11),
('Desterro do Melo', 11),
('Diamantina', 11),
('Diogo de Vasconcelos', 11),
('Dionísio', 11),
('Divinésia', 11),
('Divino', 11),
('Divino das Laranjeiras', 11),
('Divinolândia de Minas', 11),
('Divinópolis', 11),
('Divisa Alegre', 11),
('Divisa Nova', 11),
('Divisópolis', 11),
('Dom Bosco', 11),
('Dom Cavati', 11),
('Dom Joaquim', 11),
('Dom Silvério', 11),
('Dom Viçoso', 11),
('Dona Eusébia', 11),
('Dores de Campos', 11),
('Dores de Guanhães', 11),
('Dores do Indaiá', 11),
('Dores do Turvo', 11),
('Doresópolis', 11),
('Douradoquara', 11),
('Durandé', 11),
('Elói Mendes', 11),
('Engenheiro Caldas', 11),
('Engenheiro Navarro', 11),
('Entre Folhas', 11),
('Entre Rios de Minas', 11),
('Ervália', 11),
('Esmeraldas', 11),
('Espera Feliz', 11),
('Espinosa', 11),
('Espírito Santo do Dourado', 11),
('Estiva', 11),
('Estrela Dalva', 11),
('Estrela do Indaiá', 11),
('Estrela do Sul', 11),
('Eugenópolis', 11),
('Ewbank da Câmara', 11),
('Extrema', 11),
('Fama', 11),
('Faria Lemos', 11),
('Felício dos Santos', 11),
('Felisburgo', 11),
('Felixlândia', 11),
('Fernandes Tourinho', 11),
('Ferros', 11),
('Fervedouro', 11),
('Florestal', 11),
('Formiga', 11),
('Formoso', 11),
('Fortaleza de Minas', 11),
('Fortuna de Minas', 11),
('Francisco Badaró', 11),
('Francisco Dumont', 11),
('Francisco Sá', 11),
('Franciscópolis', 11),
('Frei Gaspar', 11),
('Frei Inocêncio', 11),
('Frei Lagonegro', 11),
('Fronteira', 11),
('Fronteira dos Vales', 11),
('Fruta de Leite', 11),
('Frutal', 11),
('Funilândia', 11),
('Galiléia', 11),
('Gameleiras', 11),
('Glaucilândia', 11),
('Goiabeira', 11),
('Goianá', 11),
('Gonçalves', 11),
('Gonzaga', 11),
('Gouveia', 11),
('Governador Valadares', 11),
('Grão Mogol', 11),
('Grupiara', 11),
('Guanhães', 11),
('Guapé', 11),
('Guaraciaba', 11),
('Guaraciama', 11),
('Guaranésia', 11),
('Guarani', 11),
('Guarará', 11),
('Guarda-Mor', 11),
('Guaxupé', 11),
('Guidoval', 11),
('Guimarânia', 11),
('Guiricema', 11),
('Gurinhatã', 11),
('Heliodora', 11),
('Iapu', 11),
('Ibertioga', 11),
('Ibiá', 11),
('Ibiaí', 11),
('Ibiracatu', 11),
('Ibiraci', 11),
('Ibirité', 11),
('Ibitiúra de Minas', 11),
('Ibituruna', 11),
('Icaraí de Minas', 11),
('Igarapé', 11),
('Igaratinga', 11),
('Iguatama', 11),
('Ijaci', 11),
('Ilicínea', 11),
('Imbé de Minas', 11),
('Inconfidentes', 11),
('Indaiabira', 11),
('Indianópolis', 11),
('Ingaí', 11),
('Inhapim', 11),
('Inhaúma', 11),
('Inimutaba', 11),
('Ipaba', 11),
('Ipanema', 11),
('Ipatinga', 11),
('Ipiaçu', 11),
('Ipuiúna', 11),
('Iraí de Minas', 11),
('Itabira', 11),
('Itabirinha de Mantena', 11),
('Itabirito', 11),
('Itacambira', 11),
('Itacarambi', 11),
('Itaguara', 11),
('Itaipé', 11),
('Itajubá', 11),
('Itamarandiba', 11),
('Itamarati de Minas', 11),
('Itambacuri', 11),
('Itambé do Mato Dentro', 11),
('Itamogi', 11),
('Itamonte', 11),
('Itanhandu', 11),
('Itanhomi', 11),
('Itaobim', 11),
('Itapagipe', 11),
('Itapecerica', 11),
('Itapeva', 11),
('Itatiaiuçu', 11),
('Itaú de Minas', 11),
('Itaúna', 11),
('Itaverava', 11),
('Itinga', 11),
('Itueta', 11),
('Ituiutaba', 11),
('Itumirim', 11),
('Iturama', 11),
('Itutinga', 11),
('Jaboticatubas', 11),
('Jacinto', 11),
('Jacuí', 11),
('Jacutinga', 11),
('Jaguaraçu', 11),
('Jaíba', 11),
('Jampruca', 11),
('Janaúba', 11),
('Januária', 11),
('Japaraíba', 11),
('Japonvar', 11),
('Jeceaba', 11),
('Jenipapo de Minas', 11),
('Jequeri', 11),
('Jequitaí', 11),
('Jequitibá', 11),
('Jequitinhonha', 11),
('Jesuânia', 11),
('Joaíma', 11),
('Joanésia', 11),
('João Monlevade', 11),
('João Pinheiro', 11),
('Joaquim Felício', 11),
('Jordânia', 11),
('José Gonçalves de Minas', 11),
('José Raydan', 11),
('Josenópolis', 11),
('Juatuba', 11),
('Juiz de Fora', 11),
('Juramento', 11),
('Juruaia', 11),
('Juvenília', 11),
('Ladainha', 11),
('Lagamar', 11),
('Lagoa da Prata', 11),
('Lagoa dos Patos', 11),
('Lagoa Dourada', 11),
('Lagoa Formosa', 11),
('Lagoa Grande', 11),
('Lagoa Santa', 11),
('Lajinha', 11),
('Lambari', 11);