/*
USE colorcommercedb;
*/
INSERT INTO cidade (ci_nome, ci_es_cod) VALUES
('Lamim', 11),
('Laranjal', 11),
('Lassance', 11),
('Lavras', 11),
('Leandro Ferreira', 11),
('Leme do Prado', 11),
('Leopoldina', 11),
('Liberdade', 11),
('Lima Duarte', 11),
('Limeira do Oeste', 11),
('Lontra', 11),
('Luisburgo', 11),
('Luislândia', 11),
('Luminárias', 11),
('Luz', 11),
('Machacalis', 11),
('Machado', 11),
('Madre de Deus de Minas', 11),
('Malacacheta', 11),
('Mamonas', 11),
('Manga', 11),
('Manhuaçu', 11),
('Manhumirim', 11),
('Mantena', 11),
('Mar de Espanha', 11),
('Maravilhas', 11),
('Maria da Fé', 11),
('Mariana', 11),
('Marilac', 11),
('Mário Campos', 11),
('Maripá de Minas', 11),
('Marliéria', 11),
('Marmelópolis', 11),
('Martinho Campos', 11),
('Martins Soares', 11),
('Mata Verde', 11),
('Materlândia', 11),
('Mateus Leme', 11),
('Mathias Lobato', 11),
('Matias Barbosa', 11),
('Matias Cardoso', 11),
('Matipó', 11),
('Mato Verde', 11),
('Matozinhos', 11),
('Matutina', 11),
('Medeiros', 11),
('Medina', 11),
('Mendes Pimentel', 11),
('Mercês', 11),
('Mesquita', 11),
('Minas Novas', 11),
('Minduri', 11),
('Mirabela', 11),
('Miradouro', 11),
('Miraí', 11),
('Miravânia', 11),
('Moeda', 11),
('Moema', 11),
('Monjolos', 11),
('Monsenhor Paulo', 11),
('Montalvânia', 11),
('Monte Alegre de Minas', 11),
('Monte Azul', 11),
('Monte Belo', 11),
('Monte Carmelo', 11),
('Monte Formoso', 11),
('Monte Santo de Minas', 11),
('Monte Sião', 11),
('Montes Claros', 11),
('Montezuma', 11),
('Morada Nova de Minas', 11),
('Morro da Garça', 11),
('Morro do Pilar', 11),
('Munhoz', 11),
('Muriaé', 11),
('Mutum', 11),
('Muzambinho', 11),
('Nacip Raydan', 11),
('Nanuque', 11),
('Naque', 11),
('Natalândia', 11),
('Natércia', 11),
('Nazareno', 11),
('Nepomuceno', 11),
('Ninheira', 11),
('Nova Belém', 11),
('Nova Era', 11),
('Nova Lima', 11),
('Nova Módica', 11),
('Nova Ponte', 11),
('Nova Porteirinha', 11),
('Nova Resende', 11),
('Nova Serrana', 11),
('Nova União', 11),
('Novo Cruzeiro', 11),
('Novo Oriente de Minas', 11),
('Novorizonte', 11),
('Olaria', 11),
('Olhos-d`Água', 11),
('Olímpio Noronha', 11),
('Oliveira', 11),
('Oliveira Fortes', 11),
('Onça de Pitangui', 11),
('Oratórios', 11),
('Orizânia', 11),
('Ouro Branco', 11),
('Ouro Fino', 11),
('Ouro Preto', 11),
('Ouro Verde de Minas', 11),
('Padre Carvalho', 11),
('Padre Paraíso', 11),
('Pai Pedro', 11),
('Paineiras', 11),
('Pains', 11),
('Paiva', 11),
('Palma', 11),
('Palmópolis', 11),
('Papagaios', 11),
('Pará de Minas', 11),
('Paracatu', 11),
('Paraguaçu', 11),
('Paraisópolis', 11),
('Paraopeba', 11),
('Passa Quatro', 11),
('Passa Tempo', 11),
('Passabém', 11),
('Passa-Vinte', 11),
('Passos', 11),
('Patis', 11),
('Patos de Minas', 11),
('Patrocínio', 11),
('Patrocínio do Muriaé', 11),
('Paula Cândido', 11),
('Paulistas', 11),
('Pavão', 11),
('Peçanha', 11),
('Pedra Azul', 11),
('Pedra Bonita', 11),
('Pedra do Anta', 11),
('Pedra do Indaiá', 11),
('Pedra Dourada', 11),
('Pedralva', 11),
('Pedras de Maria da Cruz', 11),
('Pedrinópolis', 11),
('Pedro Leopoldo', 11),
('Pedro Teixeira', 11),
('Pequeri', 11),
('Pequi', 11),
('Perdigão', 11),
('Perdizes', 11),
('Perdões', 11),
('Periquito', 11),
('Pescador', 11),
('Piau', 11),
('Piedade de Caratinga', 11),
('Piedade de Ponte Nova', 11),
('Piedade do Rio Grande', 11),
('Piedade dos Gerais', 11),
('Pimenta', 11),
('Pingo-d`Água', 11),
('Pintópolis', 11),
('Piracema', 11),
('Pirajuba', 11),
('Piranga', 11),
('Piranguçu', 11),
('Piranguinho', 11),
('Pirapetinga', 11),
('Pirapora', 11),
('Piraúba', 11),
('Pitangui', 11),
('Piumhi', 11),
('Planura', 11),
('Poço Fundo', 11),
('Poços de Caldas', 11),
('Pocrane', 11),
('Pompéu', 11),
('Ponte Nova', 11),
('Ponto Chique', 11),
('Ponto dos Volantes', 11),
('Porteirinha', 11),
('Porto Firme', 11),
('Poté', 11),
('Pouso Alegre', 11),
('Pouso Alto', 11),
('Prados', 11),
('Prata', 11),
('Pratápolis', 11),
('Pratinha', 11),
('Presidente Bernardes', 11),
('Presidente Juscelino', 11),
('Presidente Kubitschek', 11),
('Presidente Olegário', 11),
('Prudente de Morais', 11),
('Quartel Geral', 11),
('Queluzito', 11),
('Raposos', 11),
('Raul Soares', 11),
('Recreio', 11),
('Reduto', 11),
('Resende Costa', 11),
('Resplendor', 11),
('Ressaquinha', 11),
('Riachinho', 11),
('Riacho dos Machados', 11),
('Ribeirão das Neves', 11),
('Ribeirão Vermelho', 11),
('Rio Acima', 11),
('Rio Casca', 11),
('Rio do Prado', 11),
('Rio Doce', 11),
('Rio Espera', 11),
('Rio Manso', 11),
('Rio Novo', 11),
('Rio Paranaíba', 11),
('Rio Pardo de Minas', 11),
('Rio Piracicaba', 11),
('Rio Pomba', 11),
('Rio Preto', 11),
('Rio Vermelho', 11),
('Ritápolis', 11),
('Rochedo de Minas', 11),
('Rodeiro', 11),
('Romaria', 11),
('Rosário da Limeira', 11),
('Rubelita', 11),
('Rubim', 11),
('Sabará', 11),
('Sabinópolis', 11),
('Sacramento', 11),
('Salinas', 11),
('Salto da Divisa', 11),
('Santa Bárbara', 11),
('Santa Bárbara do Leste', 11),
('Santa Bárbara do Monte Verde', 11),
('Santa Bárbara do Tugúrio', 11),
('Santa Cruz de Minas', 11),
('Santa Cruz de Salinas', 11),
('Santa Cruz do Escalvado', 11),
('Santa Efigênia de Minas', 11),
('Santa Fé de Minas', 11),
('Santa Helena de Minas', 11),
('Santa Juliana', 11),
('Santa Luzia', 11),
('Santa Margarida', 11),
('Santa Maria de Itabira', 11),
('Santa Maria do Salto', 11),
('Santa Maria do Suaçuí', 11),
('Santa Rita de Caldas', 11),
('Santa Rita de Ibitipoca', 11),
('Santa Rita de Jacutinga', 11),
('Santa Rita de Minas', 11),
('Santa Rita do Itueto', 11),
('Santa Rita do Sapucaí', 11),
('Santa Rosa da Serra', 11),
('Santa Vitória', 11),
('Santana da Vargem', 11),
('Santana de Cataguases', 11),
('Santana de Pirapama', 11),
('Santana do Deserto', 11),
('Santana do Garambéu', 11),
('Santana do Jacaré', 11),
('Santana do Manhuaçu', 11),
('Santana do Paraíso', 11),
('Santana do Riacho', 11),
('Santana dos Montes', 11),
('Santo Antônio do Amparo', 11),
('Santo Antônio do Aventureiro', 11),
('Santo Antônio do Grama', 11),
('Santo Antônio do Itambé', 11),
('Santo Antônio do Jacinto', 11),
('Santo Antônio do Monte', 11),
('Santo Antônio do Retiro', 11),
('Santo Antônio do Rio Abaixo', 11),
('Santo Hipólito', 11),
('Santos Dumont', 11),
('São Bento Abade', 11),
('São Brás do Suaçuí', 11),
('São Domingos das Dores', 11),
('São Domingos do Prata', 11),
('São Félix de Minas', 11),
('São Francisco', 11),
('São Francisco de Paula', 11),
('São Francisco de Sales', 11),
('São Francisco do Glória', 11),
('São Geraldo', 11),
('São Geraldo da Piedade', 11),
('São Geraldo do Baixio', 11),
('São Gonçalo do Abaeté', 11),
('São Gonçalo do Pará', 11),
('São Gonçalo do Rio Abaixo', 11),
('São Gonçalo do Rio Preto', 11),
('São Gonçalo do Sapucaí', 11),
('São Gotardo', 11),
('São João Batista do Glória', 11),
('São João da Lagoa', 11),
('São João da Mata', 11),
('São João da Ponte', 11),
('São João das Missões', 11),
('São João del Rei', 11),
('São João do Manhuaçu', 11),
('São João do Manteninha', 11),
('São João do Oriente', 11),
('São João do Pacuí', 11),
('São João do Paraíso', 11),
('São João Evangelista', 11),
('São João Nepomuceno', 11),
('São Joaquim de Bicas', 11),
('São José da Barra', 11),
('São José da Lapa', 11),
('São José da Safira', 11),
('São José da Varginha', 11),
('São José do Alegre', 11),
('São José do Divino', 11),
('São José do Goiabal', 11),
('São José do Jacuri', 11),
('São José do Mantimento', 11),
('São Lourenço', 11),
('São Miguel do Anta', 11),
('São Pedro da União', 11),
('São Pedro do Suaçuí', 11),
('São Pedro dos Ferros', 11),
('São Romão', 11),
('São Roque de Minas', 11),
('São Sebastião da Bela Vista', 11),
('São Sebastião da Vargem Alegre', 11),
('São Sebastião do Anta', 11),
('São Sebastião do Maranhão', 11),
('São Sebastião do Oeste', 11),
('São Sebastião do Paraíso', 11),
('São Sebastião do Rio Preto', 11),
('São Sebastião do Rio Verde', 11),
('São Thomé das Letras', 11),
('São Tiago', 11),
('São Tomás de Aquino', 11),
('São Vicente de Minas', 11),
('Sapucaí-Mirim', 11),
('Sardoá', 11),
('Sarzedo', 11),
('Sem-Peixe', 11),
('Senador Amaral', 11),
('Senador Cortes', 11),
('Senador Firmino', 11),
('Senador José Bento', 11),
('Senador Modestino Gonçalves', 11),
('Senhora de Oliveira', 11),
('Senhora do Porto', 11),
('Senhora dos Remédios', 11),
('Sericita', 11),
('Seritinga', 11),
('Serra Azul de Minas', 11),
('Serra da Saudade', 11),
('Serra do Salitre', 11),
('Serra dos Aimorés', 11),
('Serrania', 11),
('Serranópolis de Minas', 11),
('Serranos', 11),
('Serro', 11),
('Sete Lagoas', 11),
('Setubinha', 11),
('Silveirânia', 11),
('Silvianópolis', 11),
('Simão Pereira', 11),
('Simonésia', 11),
('Sobrália', 11),
('Soledade de Minas', 11),
('Tabuleiro', 11),
('Taiobeiras', 11),
('Taparuba', 11),
('Tapira', 11),
('Tapiraí', 11),
('Taquaraçu de Minas', 11),
('Tarumirim', 11),
('Teixeiras', 11),
('Teófilo Otoni', 11),
('Timóteo', 11),
('Tiradentes', 11),
('Tiros', 11),
('Tocantins', 11),
('Tocos do Moji', 11),
('Toledo', 11),
('Tombos', 11),
('Três Corações', 11),
('Três Marias', 11),
('Três Pontas', 11),
('Tumiritinga', 11),
('Tupaciguara', 11),
('Turmalina', 11),
('Turvolândia', 11),
('Ubá', 11),
('Ubaí', 11),
('Ubaporanga', 11),
('Uberaba', 11),
('Uberlândia', 11),
('Umburatiba', 11),
('Unaí', 11),
('União de Minas', 11),
('Uruana de Minas', 11),
('Urucânia', 11),
('Urucuia', 11),
('Vargem Alegre', 11),
('Vargem Bonita', 11),
('Vargem Grande do Rio Pardo', 11),
('Varginha', 11),
('Varjão de Minas', 11),
('Várzea da Palma', 11),
('Varzelândia', 11),
('Vazante', 11),
('Verdelândia', 11),
('Veredinha', 11),
('Veríssimo', 11),
('Vermelho Novo', 11),
('Vespasiano', 11),
('Viçosa', 11),
('Vieiras', 11),
('Virgem da Lapa', 11),
('Virgínia', 11),
('Virginópolis', 11),
('Virgolândia', 11),
('Visconde do Rio Branco', 11),
('Volta Grande', 11),
('Wenceslau Braz', 11),
('Abaetetuba', 14),
('Abel Figueiredo', 14),
('Acará', 14),
('Afuá', 14),
('Água Azul do Norte', 14),
('Alenquer', 14),
('Almeirim', 14),
('Altamira', 14),
('Anajás', 14),
('Ananindeua', 14),
('Anapu', 14),
('Augusto Corrêa', 14),
('Aurora do Pará', 14),
('Aveiro', 14),
('Bagre', 14),
('Baião', 14),
('Bannach', 14),
('Barcarena', 14),
('Belém', 14),
('Belterra', 14),
('Benevides', 14),
('Bom Jesus do Tocantins', 14),
('Bonito', 14),
('Bragança', 14),
('Brasil Novo', 14),
('Brejo Grande do Araguaia', 14),
('Breu Branco', 14),
('Breves', 14),
('Bujaru', 14),
('Cachoeira do Arari', 14),
('Cachoeira do Piriá', 14),
('Cametá', 14),
('Canaã dos Carajás', 14),
('Capanema', 14),
('Capitão Poço', 14),
('Castanhal', 14),
('Chaves', 14),
('Colares', 14),
('Conceição do Araguaia', 14),
('Concórdia do Pará', 14),
('Cumaru do Norte', 14),
('Curionópolis', 14),
('Curralinho', 14),
('Curuá', 14),
('Curuçá', 14),
('Dom Eliseu', 14),
('Eldorado dos Carajás', 14),
('Faro', 14),
('Floresta do Araguaia', 14),
('Garrafão do Norte', 14),
('Goianésia do Pará', 14),
('Gurupá', 14),
('Igarapé-Açu', 14),
('Igarapé-Miri', 14),
('Inhangapi', 14),
('Ipixuna do Pará', 14),
('Irituia', 14),
('Itaituba', 14),
('Itupiranga', 14),
('Jacareacanga', 14),
('Jacundá', 14),
('Juruti', 14),
('Limoeiro do Ajuru', 14),
('Mãe do Rio', 14),
('Magalhães Barata', 14),
('Marabá', 14),
('Maracanã', 14),
('Marapanim', 14),
('Marituba', 14),
('Medicilândia', 14),
('Melgaço', 14),
('Mocajuba', 14),
('Moju', 14),
('Monte Alegre', 14),
('Muaná', 14),
('Nova Esperança do Piriá', 14),
('Nova Ipixuna', 14),
('Nova Timboteua', 14),
('Novo Progresso', 14),
('Novo Repartimento', 14),
('Óbidos', 14),
('Oeiras do Pará', 14),
('Oriximiná', 14),
('Ourém', 14),
('Ourilândia do Norte', 14),
('Pacajá', 14),
('Palestina do Pará', 14),
('Paragominas', 14),
('Parauapebas', 14),
('Pau d`Arco', 14),
('Peixe-Boi', 14),
('Piçarra', 14),
('Placas', 14),
('Ponta de Pedras', 14),
('Portel', 14),
('Porto de Moz', 14),
('Prainha', 14),
('Primavera', 14),
('Quatipuru', 14),
('Redenção', 14),
('Rio Maria', 14),
('Rondon do Pará', 14),
('Rurópolis', 14),
('Salinópolis', 14),
('Salvaterra', 14),
('Santa Bárbara do Pará', 14),
('Santa Cruz do Arari', 14),
('Santa Isabel do Pará', 14),
('Santa Luzia do Pará', 14),
('Santa Maria das Barreiras', 14),
('Santa Maria do Pará', 14),
('Santana do Araguaia', 14),
('Santarém', 14),
('Santarém Novo', 14),
('Santo Antônio do Tauá', 14),
('São Caetano de Odivelas', 14),
('São Domingos do Araguaia', 14),
('São Domingos do Capim', 14),
('São Félix do Xingu', 14),
('São Francisco do Pará', 14),
('São Geraldo do Araguaia', 14),
('São João da Ponta', 14),
('São João de Pirabas', 14),
('São João do Araguaia', 14),
('São Miguel do Guamá', 14),
('São Sebastião da Boa Vista', 14),
('Sapucaia', 14),
('Senador José Porfírio', 14),
('Soure', 14),
('Tailândia', 14),
('Terra Alta', 14),
('Terra Santa', 14),
('Tomé-Açu', 14),
('Tracuateua', 14),
('Trairão', 14),
('Tucumã', 14),
('Tucuruí', 14),
('Ulianópolis', 14),
('Uruará', 14),
('Vigia', 14),
('Viseu', 14),
('Vitória do Xingu', 14),
('Xinguara', 14),
('Água Branca', 15),
('Aguiar', 15),
('Alagoa Grande', 15),
('Alagoa Nova', 15),
('Alagoinha', 15),
('Alcantil', 15),
('Algodão de Jandaíra', 15),
('Alhandra', 15),
('Amparo', 15),
('Aparecida', 15),
('Araçagi', 15),
('Arara', 15),
('Araruna', 15),
('Areia', 15),
('Areia de Baraúnas', 15),
('Areial', 15),
('Aroeiras', 15),
('Assunção', 15),
('Baía da Traição', 15),
('Bananeiras', 15),
('Baraúna', 15),
('Barra de Santa Rosa', 15),
('Barra de Santana', 15),
('Barra de São Miguel', 15),
('Bayeux', 15),
('Belém', 15),
('Belém do Brejo do Cruz', 15),
('Bernardino Batista', 15),
('Boa Ventura', 15),
('Boa Vista', 15),
('Bom Jesus', 15),
('Bom Sucesso', 15),
('Bonito de Santa Fé', 15),
('Boqueirão', 15),
('Borborema', 15),
('Brejo do Cruz', 15),
('Brejo dos Santos', 15),
('Caaporã', 15),
('Cabaceiras', 15),
('Cabedelo', 15),
('Cachoeira dos Índios', 15),
('Cacimba de Areia', 15),
('Cacimba de Dentro', 15),
('Cacimbas', 15),
('Caiçara', 15),
('Cajazeiras', 15),
('Cajazeirinhas', 15),
('Caldas Brandão', 15),
('Camalaú', 15),
('Campina Grande', 15),
('Campo de Santana', 15),
('Capim', 15),
('Caraúbas', 15),
('Carrapateira', 15),
('Casserengue', 15),
('Catingueira', 15),
('Catolé do Rocha', 15),
('Caturité', 15),
('Conceição', 15),
('Condado', 15),
('Conde', 15),
('Congo', 15),
('Coremas', 15),
('Coxixola', 15),
('Cruz do Espírito Santo', 15),
('Cubati', 15),
('Cuité', 15),
('Cuité de Mamanguape', 15),
('Cuitegi', 15),
('Curral de Cima', 15),
('Curral Velho', 15),
('Damião', 15),
('Desterro', 15),
('Diamante', 15),
('Dona Inês', 15),
('Duas Estradas', 15),
('Emas', 15),
('Esperança', 15),
('Fagundes', 15),
('Frei Martinho', 15),
('Gado Bravo', 15),
('Guarabira', 15),
('Gurinhém', 15),
('Gurjão', 15),
('Ibiara', 15),
('Igaracy', 15),
('Imaculada', 15),
('Ingá', 15),
('Itabaiana', 15),
('Itaporanga', 15),
('Itapororoca', 15),
('Itatuba', 15),
('Jacaraú', 15),
('Jericó', 15),
('João Pessoa', 15),
('Juarez Távora', 15),
('Juazeirinho', 15),
('Junco do Seridó', 15),
('Juripiranga', 15),
('Juru', 15),
('Lagoa', 15),
('Lagoa de Dentro', 15),
('Lagoa Seca', 15),
('Lastro', 15),
('Livramento', 15),
('Logradouro', 15),
('Lucena', 15),
('Mãe d`Água', 15),
('Malta', 15),
('Mamanguape', 15),
('Manaíra', 15),
('Marcação', 15),
('Mari', 15),
('Marizópolis', 15),
('Massaranduba', 15),
('Mataraca', 15),
('Matinhas', 15),
('Mato Grosso', 15),
('Maturéia', 15),
('Mogeiro', 15),
('Montadas', 15),
('Monte Horebe', 15),
('Monteiro', 15),
('Mulungu', 15),
('Natuba', 15),
('Nazarezinho', 15),
('Nova Floresta', 15),
('Nova Olinda', 15),
('Nova Palmeira', 15),
('Olho d`Água', 15),
('Olivedos', 15),
('Ouro Velho', 15),
('Parari', 15),
('Passagem', 15),
('Patos', 15),
('Paulista', 15),
('Pedra Branca', 15),
('Pedra Lavrada', 15),
('Pedras de Fogo', 15),
('Pedro Régis', 15),
('Piancó', 15),
('Picuí', 15),
('Pilar', 15),
('Pilões', 15),
('Pilõezinhos', 15),
('Pirpirituba', 15),
('Pitimbu', 15),
('Pocinhos', 15),
('Poço Dantas', 15),
('Poço de José de Moura', 15),
('Pombal', 15),
('Prata', 15),
('Princesa Isabel', 15),
('Puxinanã', 15),
('Queimadas', 15),
('Quixabá', 15),
('Remígio', 15),
('Riachão', 15),
('Riachão do Bacamarte', 15),
('Riachão do Poço', 15),
('Riacho de Santo Antônio', 15),
('Riacho dos Cavalos', 15),
('Rio Tinto', 15),
('Salgadinho', 15),
('Salgado de São Félix', 15),
('Santa Cecília', 15),
('Santa Cruz', 15),
('Santa Helena', 15),
('Santa Inês', 15),
('Santa Luzia', 15),
('Santa Rita', 15),
('Santa Teresinha', 15),
('Santana de Mangueira', 15),
('Santana dos Garrotes', 15),
('Santarém', 15),
('Santo André', 15),
('São Bentinho', 15),
('São Bento', 15),
('São Domingos de Pombal', 15),
('São Domingos do Cariri', 15),
('São Francisco', 15),
('São João do Cariri', 15),
('São João do Rio do Peixe', 15),
('São João do Tigre', 15),
('São José da Lagoa Tapada', 15),
('São José de Caiana', 15),
('São José de Espinharas', 15),
('São José de Piranhas', 15),
('São José de Princesa', 15),
('São José do Bonfim', 15),
('São José do Brejo do Cruz', 15),
('São José do Sabugi', 15),
('São José dos Cordeiros', 15),
('São José dos Ramos', 15),
('São Mamede', 15),
('São Miguel de Taipu', 15),
('São Sebastião de Lagoa de Roça', 15),
('São Sebastião do Umbuzeiro', 15),
('Sapé', 15),
('Seridó', 15),
('Serra Branca', 15),
('Serra da Raiz', 15),
('Serra Grande', 15),
('Serra Redonda', 15),
('Serraria', 15),
('Sertãozinho', 15),
('Sobrado', 15),
('Solânea', 15),
('Soledade', 15),
('Sossêgo', 15),
('Sousa', 15),
('Sumé', 15),
('Taperoá', 15),
('Tavares', 15),
('Teixeira', 15),
('Tenório', 15),
('Triunfo', 15),
('Uiraúna', 15),
('Umbuzeiro', 15),
('Várzea', 15),
('Vieirópolis', 15),
('Vista Serrana', 15),
('Zabelê', 15),
('Abatiá', 18),
('Adrianópolis', 18),
('Agudos do Sul', 18),
('Almirante Tamandaré', 18),
('Altamira do Paraná', 18),
('Alto Paraíso', 18),
('Alto Paraná', 18),
('Alto Piquiri', 18),
('Altônia', 18),
('Alvorada do Sul', 18),
('Amaporã', 18),
('Ampére', 18),
('Anahy', 18),
('Andirá', 18),
('Ângulo', 18),
('Antonina', 18),
('Antônio Olinto', 18),
('Apucarana', 18),
('Arapongas', 18),
('Arapoti', 18),
('Arapuã', 18),
('Araruna', 18),
('Araucária', 18),
('Ariranha do Ivaí', 18),
('Assaí', 18),
('Assis Chateaubriand', 18),
('Astorga', 18),
('Atalaia', 18),
('Balsa Nova', 18),
('Bandeirantes', 18),
('Barbosa Ferraz', 18),
('Barra do Jacaré', 18),
('Barracão', 18),
('Bela Vista da Caroba', 18),
('Bela Vista do Paraíso', 18),
('Bituruna', 18),
('Boa Esperança', 18),
('Boa Esperança do Iguaçu', 18),
('Boa Ventura de São Roque', 18),
('Boa Vista da Aparecida', 18),
('Bocaiúva do Sul', 18),
('Bom Jesus do Sul', 18),
('Bom Sucesso', 18),
('Bom Sucesso do Sul', 18),
('Borrazópolis', 18),
('Braganey', 18),
('Brasilândia do Sul', 18),
('Cafeara', 18),
('Cafelândia', 18),
('Cafezal do Sul', 18),
('Califórnia', 18),
('Cambará', 18),
('Cambé', 18),
('Cambira', 18),
('Campina da Lagoa', 18),
('Campina do Simão', 18),
('Campina Grande do Sul', 18),
('Campo Bonito', 18),
('Campo do Tenente', 18),
('Campo Largo', 18),
('Campo Magro', 18),
('Campo Mourão', 18),
('Cândido de Abreu', 18),
('Candói', 18),
('Cantagalo', 18),
('Capanema', 18),
('Capitão Leônidas Marques', 18),
('Carambeí', 18),
('Carlópolis', 18),
('Cascavel', 18),
('Castro', 18),
('Catanduvas', 18),
('Centenário do Sul', 18),
('Cerro Azul', 18),
('Céu Azul', 18),
('Chopinzinho', 18),
('Cianorte', 18),
('Cidade Gaúcha', 18),
('Clevelândia', 18),
('Colombo', 18),
('Colorado', 18),
('Congonhinhas', 18),
('Conselheiro Mairinck', 18),
('Contenda', 18),
('Corbélia', 18),
('Cornélio Procópio', 18),
('Coronel Domingos Soares', 18),
('Coronel Vivida', 18),
('Corumbataí do Sul', 18),
('Cruz Machado', 18),
('Cruzeiro do Iguaçu', 18),
('Cruzeiro do Oeste', 18),
('Cruzeiro do Sul', 18),
('Cruzmaltina', 18),
('Curitiba', 18),
('Curiúva', 18),
('Diamante d`Oeste', 18),
('Diamante do Norte', 18),
('Diamante do Sul', 18),
('Dois Vizinhos', 18),
('Douradina', 18),
('Doutor Camargo', 18),
('Doutor Ulysses', 18),
('Enéas Marques', 18),
('Engenheiro Beltrão', 18),
('Entre Rios do Oeste', 18),
('Esperança Nova', 18),
('Espigão Alto do Iguaçu', 18),
('Farol', 18),
('Faxinal', 18),
('Fazenda Rio Grande', 18),
('Fênix', 18),
('Fernandes Pinheiro', 18),
('Figueira', 18),
('Flor da Serra do Sul', 18),
('Floraí', 18),
('Floresta', 18),
('Florestópolis', 18),
('Flórida', 18),
('Formosa do Oeste', 18),
('Foz do Iguaçu', 18),
('Foz do Jordão', 18),
('Francisco Alves', 18),
('Francisco Beltrão', 18),
('General Carneiro', 18),
('Godoy Moreira', 18),
('Goioerê', 18),
('Goioxim', 18),
('Grandes Rios', 18),
('Guaíra', 18),
('Guairaçá', 18),
('Guamiranga', 18),
('Guapirama', 18),
('Guaporema', 18),
('Guaraci', 18),
('Guaraniaçu', 18),
('Guarapuava', 18),
('Guaraqueçaba', 18),
('Guaratuba', 18),
('Honório Serpa', 18),
('Ibaiti', 18),
('Ibema', 18),
('Ibiporã', 18),
('Icaraíma', 18),
('Iguaraçu', 18),
('Iguatu', 18),
('Imbaú', 18),
('Imbituva', 18),
('Inácio Martins', 18),
('Inajá', 18),
('Indianópolis', 18),
('Ipiranga', 18),
('Iporã', 18),
('Iracema do Oeste', 18),
('Irati', 18),
('Iretama', 18),
('Itaguajé', 18),
('Itaipulândia', 18),
('Itambaracá', 18),
('Itambé', 18),
('Itapejara d`Oeste', 18),
('Itaperuçu', 18),
('Itaúna do Sul', 18),
('Ivaí', 18),
('Ivaiporã', 18),
('Ivaté', 18),
('Ivatuba', 18),
('Jaboti', 18),
('Jacarezinho', 18),
('Jaguapitã', 18),
('Jaguariaíva', 18),
('Jandaia do Sul', 18),
('Janiópolis', 18),
('Japira', 18),
('Japurá', 18),
('Jardim Alegre', 18),
('Jardim Olinda', 18),
('Jataizinho', 18),
('Jesuítas', 18),
('Joaquim Távora', 18),
('Jundiaí do Sul', 18),
('Juranda', 18),
('Jussara', 18),
('Kaloré', 18),
('Lapa', 18),
('Laranjal', 18),
('Laranjeiras do Sul', 18),
('Leópolis', 18),
('Lidianópolis', 18),
('Lindoeste', 18),
('Loanda', 18),
('Lobato', 18),
('Londrina', 18),
('Luiziana', 18),
('Lunardelli', 18),
('Lupionópolis', 18),
('Mallet', 18),
('Mamborê', 18),
('Mandaguaçu', 18),
('Mandaguari', 18),
('Mandirituba', 18),
('Manfrinópolis', 18),
('Mangueirinha', 18),
('Manoel Ribas', 18),
('Marechal Cândido Rondon', 18),
('Maria Helena', 18),
('Marialva', 18),
('Marilândia do Sul', 18),
('Marilena', 18),
('Mariluz', 18),
('Maringá', 18),
('Mariópolis', 18);